import { LocalizedPage, LocalizedProduct, ProductCategory, LocalizedNewsArticle, MediaFile, UserAdmin, AuditLog } from '../types/domain';

export const MOCK_CATEGORIES: ProductCategory[] = [
  {
    id: 'round-cans',
    slug: 'round-cans',
    sortOrder: 1,
    name: 'กระป๋องกลม (Round Cans)',
    description: 'กระป๋องโลหะทรงกลมมาตรฐานสำหรับอาหารและอุตสาหกรรม ปลอดสาร BPA-NI',
    translations: {
      en: { title: 'Round Cans', description: 'Food-grade tinplate containers and cylindrical cans, BPA-NI certified' },
      jp: { title: '丸缶', description: '食品・飲料用BPAフリー金属丸缶、レトルト殺菌対応' },
      cn: { title: '圆罐', description: '食品级马口铁圆罐，BPA-NI安全认证' },
      mm: { title: 'အဝိုင်းပုံ သံဗူး', description: 'အစားအသောက်နှင့် အဖျော်ယမကာများအတွက် စံချိန်မီ အဝိုင်းပုံ သံဗူးများ' },
    },
  },
  {
    id: 'rect-cans',
    slug: 'rect-cans',
    sortOrder: 2,
    name: 'กระป๋องเหลี่ยม (Rectangular Cans)',
    description: 'กระป๋องเหลี่ยมและถังเคมีภัณฑ์ มาตรฐาน UN',
    translations: {
      en: { title: 'Rectangular Cans', description: 'Heavy-duty UN certified industrial rectangular cans and pails' },
      jp: { title: '角缶', description: '高耐久UN認証産業用角型缶・ペール缶' },
      cn: { title: '方罐', description: '重型UN联合国认证工业涂料桶与方形金属罐' },
      mm: { title: 'လေးထောင့် သံဗူး', description: 'UN လက်မှတ်ရ စက်မှုလုပ်ငန်းသုံး လေးထောင့်သံဗူးများနှင့် သံပုံးများ' },
    },
  },
  {
    id: 'can-lids',
    slug: 'can-lids',
    sortOrder: 3,
    name: 'ฝาปิดกระป๋อง (Can Lids)',
    description: 'ฝาเปิดง่าย EOE และฝาโลหะทุกชนิด',
    translations: {
      en: { title: 'Can Lids & Closures', description: 'Easy Open Ends (EOE) & metal closures' },
      jp: { title: '缶蓋・キャップ', description: 'イージーオープン蓋（EOE）および各種金属キャップ' },
      cn: { title: '密封盖', description: '易拉盖 (EOE) 及各类金属密封盖' },
      mm: { title: 'သံဗူးအဖုံးများ', description: 'အလွယ်တကူဖွင့်နိုင်သော သံဗူးအဖုံးများနှင့် သတ္တုအဖုံးများ' },
    },
  },
  {
    id: 'can-ends',
    slug: 'can-ends',
    sortOrder: 4,
    name: 'ก้นกระป๋อง (Can Ends)',
    description: 'ก้นกระป๋องโลหะเคลือบสารกันสนิมมาตรฐานสากล',
    translations: {
      en: { title: 'Can Ends', description: 'Sanitary metal bottom ends for high-speed seaming' },
      jp: { title: '缶底', description: '高精度シーミング用防錆金属缶底' },
      cn: { title: '罐底', description: '高速卷封精密防锈食品级罐底' },
      mm: { title: 'သံဗူးအောက်ခြေ', description: 'အဆင့်မြင့် ဂဟေဆက်နိုင်သော သံဗူးအောက်ခြေများ' },
    },
  },
  {
    id: 'printed-cans',
    slug: 'printed-cans',
    sortOrder: 5,
    name: 'กระป๋องพิมพ์ลาย (Printed Cans)',
    description: 'กระป๋องโลหะพิมพ์ลาย 6 สี ระบบ UV Offset คุณภาพสูง',
    translations: {
      en: { title: 'Printed Cans', description: 'Ultra-HD 6-color UV offset printed decorative cans' },
      jp: { title: '印刷缶', description: '高精細6色UVオフセット印刷加飾缶' },
      cn: { title: '印花金属罐', description: '高精度六色UV胶印个性化定制印铁包装罐' },
      mm: { title: 'ဒီဇိုင်းပုံနှိပ် သံဗူးများ', description: '၆ ရောင်စုံ ခရမ်းလွန်ရောင်ခြည်သုံး ပုံနှိပ်သံဗူးများ' },
    },
  },
];

export const MOCK_PRODUCTS: LocalizedProduct[] = [
  {
    id: 'prod-1',
    categoryId: 'cat-1',
    categoryName: 'Food & Beverage Cans',
    categorySlug: 'food-beverage-cans',
    sku: 'LK-CAN-300-401',
    language: 'th',
    name: 'กระป๋องอาหารสำเร็จรูป ขนาดมาตรฐาน 300x401',
    slug: 'standard-food-can-300x401',
    description: 'กระป๋องโลหะ 3 ชิ้นเกรดพรีเมียม เคลือบแล็กเกอร์ฟู้ดเกรด ปลอดสารก่อมะเร็ง BPA-NI เหมาะสำหรับปลากระป๋อง ผลไม้แปรรูป และซอสปรุงรส',
    features: 'ทนความร้อนสูงในการสเตอริไลซ์ (121°C Retort), ป้องกันแสงและออกซิเจน 100%, พิมพ์ลายออฟเซ็ต 6 สีความละเอียดสูง',
    applications: 'ปลากระป๋อง (ทูน่า, ซาร์ดีน), ผลไม้แปรรูป (สับปะรด, เงาะ), ซอสมะเขือเทศ, ซุปสำเร็จรูป',
    material: 'Electrolytic Tinplate (ETP) 0.20mm',
    coatingType: 'BPA-NI Gold Epoxy Lacquer',
    specifications: {
      diameter_mm: 73.0,
      height_mm: 105.0,
      volume_ml: 425,
      can_type: '3-Piece Welded Sanitary Can',
      seaming: 'Double Seam ISO 9001',
      temper: 'TH330 / T4',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584727638084-5f43df65e49f?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-CAN-300-401.pdf',
    translations: {
      en: {
        name: 'Standard Sanitary Food Can 300x401',
        description: 'Premium 3-piece welded food can with food-grade BPA-NI gold lacquer coating. Engineered for canned seafood, fruits, and sauces.',
        features: 'High thermal resistance for autoclave retort (121°C), 100% light & oxygen hermetic barrier, ultra-HD 6-color offset printing.',
        applications: 'Canned fish (tuna, sardines), processed fruits (pineapple, rambutan), tomato sauce, ready soups.',
      },
      jp: {
        name: '標準3ピース食品缶 300x401',
        description: '食品グレードBPAフリーの金ラッカーを内面コーティングした高品質3ピース製缶。水産缶詰、果実加工品、調味ソースに最適です。',
        features: '121°Cオートクレーブ殺菌耐熱性、光・酸素遮断性100%、高精細6色オフセットUV印刷。',
        applications: '魚介缶詰 (ツナ、イワシ)、加工フルーツ (パイナップル、ランブータン)、トマトペースト、レトルトスープ。',
      },
      cn: {
        name: '标准三片装食品罐 300x401',
        description: '高端三片式焊接食品罐，内壁涂覆食品级BPA-NI环保金漆，适用于水产海鲜、罐头水果及浓缩酱料。',
        features: '耐121°C高温高压杀菌 (Retort)，100%隔绝光线与氧气，高精度6色UV胶印。',
        applications: '鱼类罐头 (金枪鱼、沙丁鱼)、热带水果 (菠萝、红毛丹)、番茄酱、即食浓汤。',
      },
      mm: {
        name: 'စံချိန်မီ သတ္တု အစားအသောက်ဘူး 300x401',
        description: 'အစားအသောက်အဆင့် BPA-NI ရွှေရောင်ဆေးဖြင့် အတွင်းပိုင်းသုတ်ထားသော အဆင့်မြင့် ၃ ပိုင်းစပ် သံဗူးဖြစ်ပါသည်။ ငါးသေတ္တာ၊ သစ်သီးနှင့် ဆော့စ်များအတွက် အထူးသင့်လျော်သည်။',
        features: '၁၂၁ ဒီဂရီ အပူချိန်ဒဏ်ခံနိုင်ခြင်း၊ အလင်းနှင့် လေကို ၁၀၀% ကာကွယ်ပေးခြင်း၊ ၆ ရောင် ပုံနှိပ်စနစ်။',
        applications: 'ငါးသေတ္တာ (တူနာ၊ ဆာဒင်း)၊ သစ်သီးဗူး (နာနတ်သီး၊ ကြက်မောက်သီး)၊ ခရမ်းချဉ်သီးဆော့စ်။',
      },
    },
  },
  {
    id: 'prod-2',
    categoryId: 'cat-2',
    categoryName: 'Chemical & Paint Pails',
    categorySlug: 'chemical-paint-pails',
    sku: 'LK-PAIL-20L-IND',
    language: 'th',
    name: 'ถังโลหะบรรจุเคมีภัณฑ์ ขนาด 20 ลิตร (UN Certified)',
    slug: 'industrial-chemical-pail-20l',
    description: 'ถังเหล็กทรงสอบขนาด 20 ลิตร ฝาล็อคคันโยก มาตรฐาน UN สำหรับบรรจุสารเคมี ทินเนอร์ สีน้ำมัน และน้ำมันหล่อลื่น',
    features: 'มาตรฐาน UN สำหรับการขนส่งสารอันตราย, ซีลยาง EPDM กันรั่วซึม 100%, ทนการกัดกร่อนจากตัวทำละลายอินทรีย์',
    applications: 'สีอุตสาหกรรม, ทินเนอร์, เรซิ่น, กาว, น้ำมันเครื่อง, เคมีเกษตร',
    material: 'Heavy-gauge Cold Rolled Steel / Tinplate 0.38mm',
    coatingType: 'High Chemical Resistant Phenolic Lining',
    specifications: {
      capacity_liters: 20,
      diameter_top_mm: 298.0,
      diameter_bottom_mm: 275.0,
      height_mm: 370.0,
      un_rating: 'UN 1A2/Y1.4/100',
      closure_type: 'Lever Lock Ring with Gasket',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-PAIL-20L-IND.pdf',
    translations: {
      en: {
        name: '20L Industrial Chemical Pail (UN Certified)',
        description: 'Heavy-gauge tapered steel pail with lever lock ring and UN international certification for hazardous chemicals, thinners, and industrial oils.',
        features: 'UN certified for hazardous transport, 100% leak-proof EPDM rubber gasket, superior solvent resistance.',
        applications: 'Industrial coatings, solvent thinners, resins, adhesives, engine lubricants, agrochemicals.',
      },
      jp: {
        name: '20L 産業化学品用ペール缶 (UN規格認証)',
        description: 'レバーロックリングとUN国際輸送認証を備えた重防食用20Lテーパー鋼製ペール缶。化学薬品、シンナー、工業用塗料に最適です。',
        features: 'UN危険物輸送規格認証、EPDM耐薬品性ガスケットによる完全密閉、有機溶剤への卓越した耐性。',
        applications: '工業用塗料、シンナー希釈剤、エポキシ樹脂、工業用接着剤、エンジンオイル、農業化学品。',
      },
      cn: {
        name: '20升工业化工钢桶 (UN联合国认证)',
        description: '重型锥形马口铁钢桶，配杠杆式锁紧圈，符合UN联合国危险货物运输标准，适用于化工溶剂、油漆涂料及特种润滑油。',
        features: '符合UN危险品包装运输认证，EPDM环保橡胶垫圈100%防漏，卓越耐腐蚀抗溶剂性能。',
        applications: '工业涂料、稀释剂、环氧树脂、特种胶粘剂、发动机油、农用化学品。',
      },
      mm: {
        name: '၂၀ လီတာ စက်မှုလုပ်ငန်းသုံး ဓါတုပစ္စည်းပုံး (UN လက်မှတ်ရ)',
        description: 'အန္တရာယ်ရှိသော ဓါတုပစ္စည်းများ၊ ဆေးဖျော်ရည်နှင့် စက်ဆီများ သယ်ယူပို့ဆောင်ရန် UN အသိအမှတ်ပြု လက်မှတ်ရ သံပုံးဖြစ်ပါသည်။',
        features: 'UN နိုင်ငံတကာ စံချိန်စံညွှန်းမီ၊ ယိုစိမ့်မှုမရှိစေသော EPDM ရာဘာပြားပါဝင်မှု၊ ဓါတုဒဏ်ခံနိုင်ရည်မြင့်မားမှု။',
        applications: 'စက်မှုလုပ်ငန်းသုံး ဆေးသုတ်ဆေးများ၊ သင်နာ၊ ကော်၊ စက်ဆီ၊ စိုက်ပျိုးရေးဆေးများ။',
      },
    },
  },
  {
    id: 'prod-3',
    categoryId: 'cat-3',
    categoryName: 'Aerosol & Spray Cans',
    categorySlug: 'aerosol-spray-cans',
    sku: 'LK-AERO-65X190',
    language: 'th',
    name: 'กระป๋องสเปรย์ทนแรงดันสูง 65x190 มม.',
    slug: 'aerosol-can-65x190',
    description: 'กระป๋องสเปรย์ 3 ชิ้น คุณภาพสูง ทนแรงดันได้ถึง 15 บาร์ เหมาะสำหรับสเปรย์สี สเปรย์หล่อลื่น และผลิตภัณฑ์คาร์แคร์',
    features: 'ทนแรงดันระเบิดได้มากกว่า 15 บาร์ (1.5 MPa), ระบบเชื่อมตะเข็บไฟฟ้า Soudronic ความแม่นยำสูง',
    applications: 'สีสเปรย์อุตสาหกรรม, น้ำมันหล่อลื่นอเนกประสงค์, สเปรย์ล้างเบรค, ผลิตภัณฑ์ปรับอากาศ',
    material: 'Electrolytic Tinplate 0.22mm',
    coatingType: 'Internal Clear Epoxy / External White Basecoat',
    specifications: {
      diameter_mm: 65.0,
      height_mm: 190.0,
      volume_ml: 500,
      burst_pressure_bar: 15.0,
      valve_opening: '1 inch (25.4mm)',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-AERO-65X190.pdf',
    translations: {
      en: {
        name: 'High-Pressure Aerosol Can 65x190 mm',
        description: 'High-performance 3-piece aerosol container with burst pressure rating up to 15 bar, ideal for technical sprays, lubricants, and automotive maintenance.',
        features: 'Burst pressure resistance exceeding 15 bar (1.5 MPa), precision Soudronic seam welding.',
        applications: 'Industrial spray paints, multi-purpose lubricants, brake cleaners, air fresheners.',
      },
      jp: {
        name: '高耐圧エアゾールスプレー缶 65x190mm',
        description: '最大15バールの耐圧性能を誇る高性能3ピースエアゾール缶。塗料スプレー、潤滑油、自動車メンテナンス製品に最適です。',
        features: '破壊圧力15 bar (1.5 MPa) 以上、高精度Soudronicシーム溶接技術。',
        applications: '工業用カラースプレー、万能防錆潤滑剤、ブレーキクリーナー、ルームフレグランス。',
      },
      cn: {
        name: '高耐压气雾气雾剂罐 65x190毫米',
        description: '高品质三片式气雾金属罐，耐爆破压力高达15巴，广泛应用于喷漆、精密润滑剂及汽车养护用品。',
        features: '爆破承压能力超15巴 (1.5 MPa)，瑞士Soudronic高精度电阻点焊。',
        applications: '工业自喷漆、多用途防锈润滑剂、刹车清洗剂、空气清新剂。',
      },
      mm: {
        name: 'ဖိအားမြင့် စပရေးဗူး 65x190 မီလီမီတာ',
        description: 'ဖိအား ၁၅ ဘားအထိ ခံနိုင်ရည်ရှိသော အရည်အသွေးမြင့် ၃ ပိုင်းစပ် စပရေးဗူးဖြစ်ပြီး ဆေးဖြန်းဗူးများ၊ စက်ချောဆီများနှင့် ကားထိန်းသိမ်းရေးပစ္စည်းများအတွက် သင့်လျော်ပါသည်။',
        features: 'ဖိအား ၁၅ ဘားအထက် ခံနိုင်ရည်၊ တိကျသေချာသော Soudronic ဂဟေဆက်စနစ်။',
        applications: 'စက်မှုသုံး ဆေးစပရေး၊ ချောဆီစပရေး၊ ဘရိတ်ဆေးရည်၊ အမွှေးနံ့သာစပရေး။',
      },
    },
  },
  {
    id: 'prod-4',
    categoryId: 'cat-4',
    categoryName: 'Metal Closures & Lids',
    categorySlug: 'metal-closures-lids',
    sku: 'LK-EOE-300-FS',
    language: 'th',
    name: 'ฝาดึงเปิดง่าย Easy Open End (EOE) ขนาด 300',
    slug: 'easy-open-end-300',
    description: 'ฝาเปิดง่าย EOE สำหรับกระป๋องอาหาร เปิดลื่น ดึงง่าย ไม่บาดมือ ปลอดสาร BPA-NI ป้องกันออกซิเจนซึมผ่าน 100%',
    features: 'Full Aperture (เปิดเต็มฝา), ปลอดสาร BPA-NI, Compound ซีลเกรดปลอดสาร PVC, เปิดง่ายปลอดภัย',
    applications: 'ปลากระป๋อง, ผลไม้กระป๋อง, อาหารสำเร็จรูป, อาหารสัตว์เลี้ยง (Pet Food)',
    material: 'Tinplate / TFS (Tin Free Steel) with Aluminum Tab',
    coatingType: 'Food Contact Gold Epoxy Lacquer',
    specifications: {
      diameter_mm: 73.0,
      pop_force_n: '< 25 N',
      tear_force_n: '< 45 N',
      profile: 'Full Aperture Score Line',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-EOE-300-FS.pdf',
    translations: {
      en: {
        name: 'Easy Open End (EOE) Can Lid Size 300',
        description: 'Smooth, safe-edge Easy Open End (EOE) lid engineered with BPA-NI coating and 100% hermetic oxygen barrier for canned food containers.',
        features: 'Full aperture opening, BPA-NI non-intent compliance, PVC-free sealant compound.',
        applications: 'Canned seafood, canned fruits, processed meats, pet foods.',
      },
      jp: {
        name: 'イージーオープンエンド (EOE) 缶蓋 300号',
        description: '開けやすく手を切りにくいセーフティエッジ設計のイージーオープンエンド (EOE)。BPA-NIコーティングで酸素透過を100%遮断します。',
        features: 'フルアパーチャー全開式、BPA-NI対応、PVCフリー高密閉ガスケット。',
        applications: '魚介缶詰、フルーツ缶、レトルト食肉加工品、ペットフード。',
      },
      cn: {
        name: '易拉盖 Easy Open End (EOE) 300型',
        description: '全开式易拉盖 (EOE)，开启顺畅安全不割手，采用BPA-NI环保涂层，100%阻隔氧气渗透。',
        features: '全开口刻痕设计、BPA-NI环保合规、无PVC密封胶圈。',
        applications: '水产罐头、水果罐头、肉类罐头、高端宠物食品。',
      },
      mm: {
        name: 'အလွယ်တကူဖွင့်နိုင်သော သံဗူးအဖုံး EOE 300',
        description: 'အန္တရာယ်ကင်းစွာ အလွယ်တကူဖွင့်နိုင်သော EOE သံဗူးအဖုံးဖြစ်ပြီး BPA-NI အကာအကွယ်ဖြင့် အစားအသောက်များကို လတ်ဆတ်စွာ ထိန်းသိမ်းပေးပါသည်။',
        features: 'အပြည့်အဝဖွင့်နိုင်သောဒီဇိုင်း၊ BPA-NI စံချိန်မီ၊ PVC-free ပေါင်းစပ်မှု။',
        applications: 'ငါးသေတ္တာ၊ သစ်သီးဗူး၊ အသားဗူး၊ အိမ်မွေးတိရစ္ဆာန် အစာဗူးများ။',
      },
    },
  },
  {
    id: 'prod-5',
    categoryId: 'can-ends',
    categoryName: 'ก้นกระป๋องโลหะ (Can Ends)',
    categorySlug: 'can-ends',
    sku: 'LK-END-300-SAN',
    language: 'th',
    name: 'ก้นกระป๋องโลหะเคลือบกันสนิม ขนาดมาตรฐาน 300',
    slug: 'sanitary-can-ends-300',
    description: 'ก้นกระป๋องโลหะเคลือบแล็กเกอร์คุณภาพสูง สำหรับเข้าเครื่องปิดผนึก Double Seamer ปลอดสาร BPA-NI ทนความดันและสุญญากาศ',
    features: 'ขอบเรียบแม่นยำสูง, Compound ยางสังเคราะห์กันรั่วซึม 100%, ทนความร้อน Retort 121°C',
    applications: 'ก้นกระป๋องอาหาร, ปลากระป๋อง, ผักผลไม้, นมข้นหวาน',
    material: 'Electrolytic Tinplate (ETP) 0.19mm',
    coatingType: 'Internal Gold Epoxy Lacquer / External Clear',
    specifications: {
      diameter_mm: 73.0,
      thickness_mm: 0.19,
      temper: 'TH550 / DR8',
    },
    primaryImageURL: '/images/cat-can-ends.jpg',
    galleryImages: ['/images/cat-can-ends.jpg'],
    pdfSpecURL: '/specs/LK-END-300-SAN.pdf',
    translations: {
      en: {
        name: 'Standard Anti-Rust Sanitary Can Ends Size 300',
        description: 'High-quality lacquer coated metal can bottom ends engineered for precision double seamers, 100% BPA-NI compliant.',
        features: 'Precision curled edge, 100% hermetic synthetic compound sealing, retort heat resistant up to 121°C.',
        applications: 'Canned seafood, processed vegetables and fruits, condensed milk, processed meats.',
      },
      jp: {
        name: '防錆衛生用標準缶底エンド 300号',
        description: '自動巻締機（ダブルシーマー）に最適化された高品質ラッカー塗布缶底。BPA-NI対応で高耐圧・耐真空仕様。',
        features: '高精度カールエッジ、完全密閉合成ガスケット、121℃レトルト殺菌対応。',
        applications: '魚介缶詰、農産缶詰、練乳・乳製品、レトルト食肉。',
      },
      cn: {
        name: '标准防锈食品级金属罐底 300型',
        description: '优质食品级防锈马口铁罐底，专为高精度二重卷封机打造，符合BPA-NI标准，耐高压耐真空。',
        features: '精密卷边加工、100%气密性合成密封胶、耐121°C高温高压杀菌。',
        applications: '海产水产罐头、果蔬罐头、炼乳乳制品、罐装肉制品。',
      },
      mm: {
        name: 'စံချိန်မီ သံချေးတက်မှုကာကွယ် သံဗူးအောက်ခြေ 300',
        description: 'Double Seamer စက်များအတွက် အထူးသင့်လျော်သော အရည်အသွေးမြင့် သံဗူးအောက်ခြေဖြစ်ပြီး BPA-NI စံချိန်မီ အပူနှင့် ဖိအားဒဏ်ခံနိုင်ပါသည်။',
        features: 'တိကျသော အနားကွပ်ဒီဇိုင်း၊ ၁၀၀% ယိုစိမ့်မှုမရှိစေသော ရာဘာလိုင်း၊ ၁၂၁ ဒီဂရီ အပူခံနိုင်ရည်။',
        applications: 'ငါးသေတ္တာ၊ ဟင်းသီးဟင်းရွက်ဗူးများ၊ နို့ဆီဗူး၊ အသားဗူးများ။',
      },
    },
  },
  {
    id: 'prod-6',
    categoryId: 'printed-cans',
    categoryName: 'กระป๋องพิมพ์ลาย (Printed Cans)',
    categorySlug: 'printed-cans',
    sku: 'LK-PRINT-300-6C',
    language: 'th',
    name: 'กระป๋องพิมพ์ลายออฟเซ็ตความละเอียดสูง 6 สี',
    slug: 'premium-printed-can-6color',
    description: 'กระป๋องบรรจุภัณฑ์พิมพ์ลายกราฟิกพรีเมียม ด้วยระบบ Offset Printing 6 สี คมชัด สีสันสดใส เคลือบเงาป้องกันรอยขีดข่วน',
    features: 'พิมพ์ความละเอียดสูง 6 สี, เคลือบ Overprint Varnish ทนรอยขูดขีด, ยกระดับภาพลักษณ์แบรนด์',
    applications: 'อาหารพรีเมียม, ขนมขบเคี้ยว, ชา กาแฟ, ของฝากส่งออก',
    material: 'Electrolytic Tinplate (ETP) 0.20mm',
    coatingType: 'Food Grade Internal Lacquer + High Gloss External Varnish',
    specifications: {
      diameter_mm: 73.0,
      height_mm: 110.0,
      print_colors: '6 Colors CMYK + 2 Spot Colors',
    },
    primaryImageURL: '/images/cat-printed-cans.jpg',
    galleryImages: ['/images/cat-printed-cans.jpg'],
    pdfSpecURL: '/specs/LK-PRINT-300-6C.pdf',
    translations: {
      en: {
        name: '6-Color High-Definition Premium Printed Metal Can',
        description: 'Custom printed metal packaging utilizing 6-color offset printing technology with razor-sharp imagery, vibrant reproduction, and scratch-resistant gloss coating.',
        features: '6-color ultra-HD offset print, overprint scratch-resistant protective varnish, premium brand elevating appeal.',
        applications: 'Gourmet foods, luxury snacks, premium tea & coffee, export specialty items.',
      },
      jp: {
        name: '6色高精細オフセット印刷 高級金属缶',
        description: '6色オフセット印刷技術による鮮明で美しいグラフィック印刷と耐擦傷性グロスオーバーニス加工を施した高級缶パッケージ。',
        features: '高精細6色印刷、傷に強いオーバープリント保護ニス、ブランド価値を高める高級感。',
        applications: 'プレミアム食品、高級スナック、紅茶・珈琲、輸出向け贈答品。',
      },
      cn: {
        name: '六色超高清多色精细印花金属罐',
        description: '采用6色高精度胶印技术的高端马口铁金属包装，图案细腻色彩饱满，表面涂覆耐刮高光保护清漆。',
        features: '6色超高分辨率印刷、防刮耐磨高光保护漆、显著提升品牌档次。',
        applications: '高端食品、特色休闲零食、精品茶叶咖啡、出口礼品罐。',
      },
      mm: {
        name: 'အရောင် ၆ ရောင် အဆင့်မြင့်ပုံနှိပ် သံဗူး',
        description: 'Offset Printing စနစ်ဖြင့် ၆ ရောင် အလှဆင်ပုံနှိပ်ထားသော အရည်အသွေးမြင့် သံဗူးဖြစ်ပြီး ခြစ်ရာမထင်စေသော အကာအကွယ်အလွှာ ပါဝင်ပါသည်။',
        features: '၆ ရောင် အဆင့်မြင့်ပုံနှိပ်အရည်အသွေး၊ ခြစ်ရာဒဏ်ခံ အကာအကွယ်ဗားနစ်၊ အဆင့်မြင့်အမှတ်တံဆိပ်ပုံရိပ်။',
        applications: 'အဆင့်မြင့်စားသောက်ကုန်များ၊ မုန့်များ၊ လက်ဖက်ခြောက်နှင့် ကော်ဖီ၊ ပြည်ပပို့ကုန်များ။',
      },
    },
  },
];

export const MOCK_HOME_PAGE: LocalizedPage = {
  id: 'page-home',
  slug: 'home',
  language: 'th',
  title: 'ผู้นำนวัตกรรมบรรจุภัณฑ์โลหะสำหรับอาหารและอุตสาหกรรมสากล',
  metaTitle: 'บริษัท ไคโอทรอน เทคโนโลยี จำกัด | โรงงานผลิตกระป๋องและบรรจุภัณฑ์โลหะชั้นนำ',
  metaDesc: 'โรงงานผลิตกระป๋องอาหาร ถังเคมีภัณฑ์ และฝาเปิดง่าย EOE คุณภาพมาตรฐานส่งออกสากล',
  metaKeys: 'กระป๋องอาหาร, ถังเคมี, บรรจุภัณฑ์โลหะ, EOE, Chiotron',
  ogMetadata: {},
  sections: [
    {
      id: 'sec-hero',
      sectionType: 'hero',
      sortOrder: 1,
      title: 'นวัตกรรมบรรจุภัณฑ์โลหะที่แข็งแกร่ง ปลอดภัย และยั่งยืน',
      subtitle: 'บริษัท ไคโอทรอน เทคโนโลยี จำกัด ผลิตกระป๋องอาหาร ถังเคมีภัณฑ์ และฝาโลหะมาตรฐานส่งออก ด้วยเครื่องจักรอัตโนมัติความเร็วสูง',
      contentBody: 'กว่า 25 ปีแห่งความเชี่ยวชาญในการส่งมอบบรรจุภัณฑ์โลหะมาตรฐานสากลให้แก่แบรนด์ชั้นนำทั่วโลก',
      config: {
        badge: 'ISO 9001:2015 & FSSC 22000 Certified',
        ctaPrimary: { text: 'Explore Catalog', link: '/products' },
        ctaSecondary: { text: 'Contact Engineering', link: '/contact' },
        bgImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1920&q=80',
      },
      payload: {},
    },
    {
      id: 'sec-intro',
      sectionType: 'about',
      sortOrder: 2,
      title: 'มาตรฐานโรงงานและความพร้อมระดับสากล',
      subtitle: 'ตั้งอยู่บนทำเลยุทธศาสตร์อุตสาหกรรม จังหวัดสมุทรสาคร พื้นที่กว่า 25,000 ตารางเมตร',
      contentBody: 'เรามุ่งมั่นวิจัยและพัฒนาบรรจุภัณฑ์โลหะอย่างต่อเนื่อง ด้วยเครื่องจักร Soudronic สวิตเซอร์แลนด์ และระบบพิมพ์ 6 สีขั้นสูง',
      config: {
        established: 1998,
        capital: '100,000,000 THB',
      },
      payload: {},
    },
    {
      id: 'sec-strengths',
      sectionType: 'feature_cards',
      sortOrder: 3,
      title: 'จุดเด่นที่ทำให้เราเป็นที่หนึ่งในใจลูกค้า',
      subtitle: 'ความปลอดภัยเกรดอาหาร 100%, โลหะรีไซเคิลได้ไม่รู้จบ, เทคโนโลยีอัตโนมัติขั้นสูง',
      contentBody: '',
      config: {
        items: [
          { icon: 'shield-check', title: 'Food Safety 100%', desc: 'ปลอดสาร BPA-NI ผ่านการรับรองสเตอริไลซ์' },
          { icon: 'recycle', title: 'Infinitely Recyclable', desc: 'เหล็กและอลูมิเนียมรีไซเคิลได้ 100% ไม่รู้จบ' },
          { icon: 'cpu', title: 'Smart Automation AI', desc: 'กล้อง AI ตรวจสอบความแน่นของตะเข็บ 100%' },
        ],
      },
      payload: {},
    },
    {
      id: 'sec-stats',
      sectionType: 'statistics',
      sortOrder: 4,
      title: 'ตัวเลขสะท้อนความไว้วางใจและศักยภาพการผลิต',
      subtitle: 'กำลังการผลิตกว่า 120 ล้านชิ้นต่อปี ส่งมอบสู่แบรนด์ระดับประเทศและส่งออกสากล',
      contentBody: '',
      config: {
        metrics: [
          { value: '120M+', label: 'กำลังการผลิตต่อปี (ชิ้น)' },
          { value: '25,000', label: 'พื้นที่โรงงาน (ตร.ม.)' },
          { value: '25+', label: 'ปีแห่งความเชี่ยวชาญ' },
          { value: '99.98%', label: 'อัตรามาตรฐานผ่านการตรวจสอบ' },
        ],
      },
      payload: {},
    },
  ],
};

export const MOCK_NEWS: LocalizedNewsArticle[] = [
  {
    id: 'news-1',
    category: 'SUSTAINABILITY',
    language: 'th',
    title: 'ไคโอทรอน เทคโนโลยี ติดตั้งระบบ Solar Rooftop ผลิตพลังงานสะอาดลดคาร์บอน 1,200 ตันต่อปี',
    slug: 'chiotron-solar-rooftop-green-initiative',
    summary: 'เดินหน้าสู่โรงงานสีเขียวด้วยการติดตั้งแผงโซลาร์เซลล์ขนาด 1.2 MW ช่วยขับเคลื่อนการผลิตด้วยพลังงานสะอาด 100%',
    contentBody: '<p>บริษัท ไคโอทรอน เทคโนโลยี จำกัด (CHIOTRON TECHNOLOGY) ได้เสร็จสิ้นการติดตั้งระบบ Solar Rooftop ณ โรงงานจังหวัดสมุทรสาคร เพื่อมุ่งสู่ความเป็นกลางทางคาร์บอน...</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2026-08-15T09:00:00Z',
    translations: {
      en: {
        title: 'Chiotron Technology Completes 1.2 MW Solar Rooftop Installation to Cut 1,200 Tons of Carbon Annually',
        summary: 'Transitioning toward a 100% green manufacturing facility with on-site clean solar energy, reducing greenhouse emissions.',
        contentBody: '<p>CHIOTRON TECHNOLOGY CO., LTD. has successfully commissioned a 1.2 MW solar rooftop system at our Samut Sakhon manufacturing complex...</p>',
      },
      jp: {
        title: 'カイオトロン・テクノロジー、年間1,200トンのCO2を削減する1.2MW屋上太陽光発電システムを導入',
        summary: '100%クリーンエネルギーによる環境調和型グリーン工場の実現に向けた持続可能性の取り組み。',
        contentBody: '<p>カイオトロン・テクノロジー株式会社は、サムットサコーン工場において1.2MW規模の屋上太陽光発電（ソーラールーフトップ）設備の稼働を開始しました...</p>',
      },
      cn: {
        title: '凯奥创科技完成1.2兆瓦屋顶光伏系统安装，年减少碳排放1200吨',
        summary: '践行绿色低碳制造承诺，全面采用清洁太阳能能源助力可持续工业发展。',
        contentBody: '<p>凯奥创科技有限公司于龙仔厝府制造基地正式启用1.2兆瓦屋顶太阳能光伏发电系统，致力于实现全厂清洁能源供电与碳中和目标...</p>',
      },
      mm: {
        title: 'CHIOTRON TECHNOLOGY သည် တစ်နှစ်လျှင် ကာဗွန်တန်ချိန် ၁,၂၀၀ လျှော့ချမည့် 1.2 MW ဆိုလာစနစ် တပ်ဆင်ပြီးစီး',
        summary: '၁၀၀% သန့်ရှင်းသော စွမ်းအင်ဖြင့် စိမ်းလန်းသော စက်ရုံတည်ဆောက်ရေးသို့ ရှေးရှုဆောင်ရွက်ခြင်း။',
        contentBody: '<p>CHIOTRON TECHNOLOGY ကုမ္ပဏီလီမိတက်သည် စမွတ်စာခွန် စက်ရုံတွင် ၁.၂ မဂ္ဂါဝပ်ရှိ အမိုးပေါ်ဆိုလာစနစ် တပ်ဆင်လည်ပတ်ခြင်းကို အောင်မြင်စွာ ဆောင်ရွက်ပြီးစီးခဲ့ပါသည်...</p>',
      },
    },
  },
  {
    id: 'news-2',
    category: 'TECHNOLOGY',
    language: 'th',
    title: 'เปิดตัวสายการผลิตกระป๋องอาหารความเร็วสูงรุ่นใหม่ นำเข้าจากสวิตเซอร์แลนด์',
    slug: 'new-high-speed-canmaking-line',
    summary: 'เพิ่มกำลังการผลิตอีก 30% พร้อมระบบ AI Visual Inspection ตรวจสอบคุณภาพตะเข็บแบบ Real-time',
    contentBody: '<p>เพื่อรองรับการเติบโตของอุตสาหกรรมอาหารส่งออก ทางบริษัทฯ ได้ลงทุนขยายสายการผลิตกระป๋อง 3 ชิ้น ความเร็ว 600 กระป๋องต่อนาที...</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2026-07-20T10:30:00Z',
    translations: {
      en: {
        title: 'New High-Speed Swiss Canmaking Line Launched to Boost Export Capacity by 30%',
        summary: 'Featuring advanced Soudronic seam welders and real-time AI visual quality inspection, ensuring zero defect tolerance.',
        contentBody: '<p>To support surging demand across global food packaging supply chains, Chiotron Technology has expanded capacity with a new 600 cpm line...</p>',
      },
      jp: {
        title: 'スイス製最新鋭・高速製缶ラインを稼働開始、輸出向け生産能力を30%拡大',
        summary: 'Soudronic溶接機とAI画像検査システムにより、シーム欠陥のリアルタイム全数検査を実現。',
        contentBody: '<p>輸出向け食品缶詰市場の急成長に対応し、スイスSoudronic社製の最新鋭高速自動製缶ライン（分速600缶）を増設いたしました...</p>',
      },
      cn: {
        title: '引进瑞士新一代高速精密制罐生产线，出口产能提升30%',
        summary: '配备先进Soudronic电阻焊机与AI智能视觉全检系统，实现全天候高品质实时监控。',
        contentBody: '<p>为满足国际食品出口企业日益增长的高标准需求，凯奥创科技投资扩建了每分钟600罐的瑞士进口全自动三片罐生产线...</p>',
      },
      mm: {
        title: 'ဆွစ်ဇာလန်နည်းပညာသုံး အမြန်နှုန်းမြင့် သံဗူးထုတ်လုပ်ရေးလိုင်းသစ်ကို တိုးချဲ့မိတ်ဆက်',
        summary: 'AI အလိုအလျောက် စစ်ဆေးရေးစနစ်ဖြင့် ထုတ်လုပ်မှုစွမ်းရည် ၃၀% တိုးမြှင့်လိုက်ပါသည်။',
        contentBody: '<p>နိုင်ငံတကာ စားသောက်ကုန်တင်ပို့မှု ဈေးကွက်တိုးတက်မှုကို အထောက်အကူပြုရန် တစ်မိနစ်လျှင် သံဗူး ၆၀၀ ထုတ်လုပ်နိုင်သော ဆွစ်ဇာလန်စက်လိုင်းသစ်ကို တပ်ဆင်ခဲ့ပါသည်...</p>',
      },
    },
  },
];

export const MOCK_MEDIA: MediaFile[] = [
  {
    id: 'med-1',
    filename: 'food-can-300.jpg',
    originalFilename: 'food-can-300.jpg',
    bucket: 'lohakit-media',
    storageKey: 'products/2026/09/food-can-300.jpg',
    mimeType: 'image/jpeg',
    fileSize: 485000,
    width: 1200,
    height: 800,
    hashSha256: 'a1b2c3d4e5f6',
    altText: { th: 'กระป๋องอาหาร 300', en: 'Food Can 300' },
    folder: 'products',
    url: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
    uploaderName: 'Lohakit Admin',
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'med-2',
    filename: 'factory-exterior.jpg',
    originalFilename: 'factory-exterior.jpg',
    bucket: 'lohakit-media',
    storageKey: 'facility/2026/09/factory-exterior.jpg',
    mimeType: 'image/jpeg',
    fileSize: 890000,
    width: 1920,
    height: 1080,
    hashSha256: 'c7d8e9f0a1b2',
    altText: { th: 'โรงงานสมุทรสาคร', en: 'Factory Plant' },
    folder: 'facility',
    url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    uploaderName: 'Lohakit Admin',
    createdAt: '2026-08-28T14:30:00Z',
    updatedAt: '2026-08-28T14:30:00Z',
  },
];
