import { LocalizedPage, LocalizedProduct, ProductCategory, LocalizedNewsArticle, MediaFile, UserAdmin, AuditLog } from '../types/domain';

export const MOCK_CATEGORIES: ProductCategory[] = [
  { id: 'cat-1', slug: 'food-beverage-cans', sortOrder: 1, name: 'กระป๋องบรรจุอาหารและเครื่องดื่ม (Food & Beverage Cans)', description: 'Food-grade tinplate containers, BPA-NI certified' },
  { id: 'cat-2', slug: 'chemical-paint-pails', sortOrder: 2, name: 'ถังโลหะบรรจุเคมีภัณฑ์และสี (Chemical & Paint Pails)', description: 'Heavy-duty UN certified industrial drums & pails' },
  { id: 'cat-3', slug: 'aerosol-spray-cans', sortOrder: 3, name: 'กระป๋องสเปรย์และแอโรซอล (Aerosol & Spray Cans)', description: 'High-pressure resistant 3-piece aerosol cans' },
  { id: 'cat-4', slug: 'metal-closures-lids', sortOrder: 4, name: 'ฝาโลหะและฝาดึงง่าย (Metal Closures & EOE)', description: 'Easy Open Ends (EOE) & paint ring/lids' },
];

export const MOCK_PRODUCTS: LocalizedProduct[] = [
  {
    id: 'prod-1',
    categoryId: 'cat-1',
    categoryName: 'Food & Beverage Cans',
    categorySlug: 'food-beverage-cans',
    sku: 'LK-CAN-300-401',
    language: 'th',
    name: 'กระป๋องอาหารสำเร็จรูป ขนาดมาตรฐาน 300x401',
    slug: 'standard-food-can-300x401',
    description: 'กระป๋องโลหะ 3 ชิ้นเกรดพรีเมียม เคลือบแล็กเกอร์ฟู้ดเกรด ปลอดสารก่อมะเร็ง BPA-NI เหมาะสำหรับปลากระป๋อง ผลไม้แปรรูป และซอสปรุงรส',
    features: 'ทนความร้อนสูงในการสเตอริไลซ์ (121°C Retort), ป้องกันแสงและออกซิเจน 100%, พิมพ์ลายออฟเซ็ต 6 สีความละเอียดสูง',
    applications: 'ปลากระป๋อง (ทูน่า, ซาร์ดีน), ผลไม้แปรรูป (สับปะรด, เงาะ), ซอสมะเขือเทศ, ซุปสำเร็จรูป',
    material: 'Electrolytic Tinplate (ETP) 0.20mm',
    coatingType: 'BPA-NI Gold Epoxy Lacquer',
    specifications: {
      diameter_mm: 73.0,
      height_mm: 105.0,
      volume_ml: 425,
      can_type: '3-Piece Welded Sanitary Can',
      seaming: 'Double Seam ISO 9001',
      temper: 'TH330 / T4',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584727638084-5f43df65e49f?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-CAN-300-401.pdf',
  },
  {
    id: 'prod-2',
    categoryId: 'cat-2',
    categoryName: 'Chemical & Paint Pails',
    categorySlug: 'chemical-paint-pails',
    sku: 'LK-PAIL-20L-IND',
    language: 'th',
    name: 'ถังโลหะบรรจุเคมีภัณฑ์ ขนาด 20 ลิตร (UN Certified)',
    slug: 'industrial-chemical-pail-20l',
    description: 'ถังเหล็กทรงสอบขนาด 20 ลิตร ฝาล็อคคันโยก มาตรฐาน UN สำหรับบรรจุสารเคมี ทินเนอร์ สีน้ำมัน และน้ำมันหล่อลื่น',
    features: 'มาตรฐาน UN สำหรับการขนส่งสารอันตราย, ซีลยาง EPDM กันรั่วซึม 100%, ทนการกัดกร่อนจากตัวทำละลายอินทรีย์',
    applications: 'สีอุตสาหกรรม, ทินเนอร์, เรซิ่น, กาว, น้ำมันเครื่อง, เคมีเกษตร',
    material: 'Heavy-gauge Cold Rolled Steel / Tinplate 0.38mm',
    coatingType: 'High Chemical Resistant Phenolic Lining',
    specifications: {
      capacity_liters: 20,
      diameter_top_mm: 298.0,
      diameter_bottom_mm: 275.0,
      height_mm: 370.0,
      un_rating: 'UN 1A2/Y1.4/100',
      closure_type: 'Lever Lock Ring with Gasket',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-PAIL-20L-IND.pdf',
  },
  {
    id: 'prod-3',
    categoryId: 'cat-3',
    categoryName: 'Aerosol & Spray Cans',
    categorySlug: 'aerosol-spray-cans',
    sku: 'LK-AERO-65X190',
    language: 'th',
    name: 'กระป๋องสเปรย์ทนแรงดันสูง 65x190 มม.',
    slug: 'aerosol-can-65x190',
    description: 'กระป๋องสเปรย์ 3 ชิ้น คุณภาพสูง ทนแรงดันได้ถึง 15 บาร์ เหมาะสำหรับสเปรย์สี สเปรย์หล่อลื่น และผลิตภัณฑ์คาร์แคร์',
    features: 'ทนแรงดันระเบิดได้มากกว่า 15 บาร์ (1.5 MPa), ระบบเชื่อมตะเข็บไฟฟ้า Soudronic ความแม่นยำสูง',
    applications: 'สีสเปรย์อุตสาหกรรม, น้ำมันหล่อลื่นอเนกประสงค์, สเปรย์ล้างเบรค, ผลิตภัณฑ์ปรับอากาศ',
    material: 'Electrolytic Tinplate 0.22mm',
    coatingType: 'Internal Clear Epoxy / External White Basecoat',
    specifications: {
      diameter_mm: 65.0,
      height_mm: 190.0,
      volume_ml: 500,
      burst_pressure_bar: 15.0,
      valve_opening: '1 inch (25.4mm)',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-AERO-65X190.pdf',
  },
  {
    id: 'prod-4',
    categoryId: 'cat-4',
    categoryName: 'Metal Closures & Lids',
    categorySlug: 'metal-closures-lids',
    sku: 'LK-EOE-300-FS',
    language: 'th',
    name: 'ฝาดึงเปิดง่าย Easy Open End (EOE) ขนาด 300',
    slug: 'easy-open-end-300',
    description: 'ฝาเปิดง่าย EOE สำหรับกระป๋องอาหาร เปิดลื่น ดึงง่าย ไม่บาดมือ ปลอดสาร BPA-NI ป้องกันออกซิเจนซึมผ่าน 100%',
    features: 'Full Aperture (เปิดเต็มฝา), ปลอดสาร BPA-NI, Compound ซีลเกรดปลอดสาร PVC, เปิดง่ายปลอดภัย',
    applications: 'ปลากระป๋อง, ผลไม้กระป๋อง, อาหารสำเร็จรูป, อาหารสัตว์เลี้ยง (Pet Food)',
    material: 'Tinplate / TFS (Tin Free Steel) with Aluminum Tab',
    coatingType: 'Food Contact Gold Epoxy Lacquer',
    specifications: {
      diameter_mm: 73.0,
      pop_force_n: '< 25 N',
      tear_force_n: '< 45 N',
      profile: 'Full Aperture Score Line',
    },
    primaryImageURL: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    ],
    pdfSpecURL: '/specs/LK-EOE-300-FS.pdf',
  },
];

export const MOCK_HOME_PAGE: LocalizedPage = {
  id: 'page-home',
  slug: 'home',
  language: 'th',
  title: 'ผู้นำนวัตกรรมบรรจุภัณฑ์โลหะสำหรับอาหารและอุตสาหกรรมสากล',
  metaTitle: 'บริษัท โลหะกิจรุ่งเจริญทรัพย์ จำกัด | โรงงานผลิตกระป๋องและบรรจุภัณฑ์โลหะชั้นนำ',
  metaDesc: 'โรงงานผลิตกระป๋องอาหาร ถังเคมีภัณฑ์ และฝาเปิดง่าย EOE คุณภาพมาตรฐานส่งออกสากล',
  metaKeys: 'กระป๋องอาหาร, ถังเคมี, บรรจุภัณฑ์โลหะ, EOE, Lohakit',
  ogMetadata: {},
  sections: [
    {
      id: 'sec-hero',
      sectionType: 'hero',
      sortOrder: 1,
      title: 'นวัตกรรมบรรจุภัณฑ์โลหะที่แข็งแกร่ง ปลอดภัย และยั่งยืน',
      subtitle: 'บริษัท โลหะกิจรุ่งเจริญทรัพย์ จำกัด ผลิตกระป๋องอาหาร ถังเคมีภัณฑ์ และฝาโลหะมาตรฐานส่งออก ด้วยเครื่องจักรอัตโนมัติความเร็วสูง',
      contentBody: 'กว่า 25 ปีแห่งความเชี่ยวชาญในการส่งมอบบรรจุภัณฑ์โลหะมาตรฐานสากลให้แก่แบรนด์ชั้นนำทั่วโลก',
      config: {
        badge: 'ISO 9001:2015 & FSSC 22000 Certified',
        ctaPrimary: { text: 'Explore Catalog', link: '/products' },
        ctaSecondary: { text: 'Contact Engineering', link: '/contact' },
        bgImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1920&q=80',
      },
      payload: {},
    },
    {
      id: 'sec-intro',
      sectionType: 'about',
      sortOrder: 2,
      title: 'มาตรฐานโรงงานและความพร้อมระดับสากล',
      subtitle: 'ตั้งอยู่บนทำเลยุทธศาสตร์อุตสาหกรรม จังหวัดสมุทรสาคร พื้นที่กว่า 25,000 ตารางเมตร',
      contentBody: 'เรามุ่งมั่นวิจัยและพัฒนาบรรจุภัณฑ์โลหะอย่างต่อเนื่อง ด้วยเครื่องจักร Soudronic สวิตเซอร์แลนด์ และระบบพิมพ์ 6 สีขั้นสูง',
      config: {
        established: 1998,
        capital: '100,000,000 THB',
      },
      payload: {},
    },
    {
      id: 'sec-strengths',
      sectionType: 'feature_cards',
      sortOrder: 3,
      title: 'จุดเด่นที่ทำให้เราเป็นที่หนึ่งในใจลูกค้า',
      subtitle: 'ความปลอดภัยเกรดอาหาร 100%, โลหะรีไซเคิลได้ไม่รู้จบ, เทคโนโลยีอัตโนมัติขั้นสูง',
      contentBody: '',
      config: {
        items: [
          { icon: 'shield-check', title: 'Food Safety 100%', desc: 'ปลอดสาร BPA-NI ผ่านการรับรองสเตอริไลซ์' },
          { icon: 'recycle', title: 'Infinitely Recyclable', desc: 'เหล็กและอลูมิเนียมรีไซเคิลได้ 100% ไม่รู้จบ' },
          { icon: 'cpu', title: 'Smart Automation AI', desc: 'กล้อง AI ตรวจสอบความแน่นของตะเข็บ 100%' },
        ],
      },
      payload: {},
    },
    {
      id: 'sec-stats',
      sectionType: 'statistics',
      sortOrder: 4,
      title: 'ตัวเลขสะท้อนความไว้วางใจและศักยภาพการผลิต',
      subtitle: 'กำลังการผลิตกว่า 120 ล้านชิ้นต่อปี ส่งมอบสู่แบรนด์ระดับประเทศและส่งออกสากล',
      contentBody: '',
      config: {
        metrics: [
          { value: '120M+', label: 'กำลังการผลิตต่อปี (ชิ้น)' },
          { value: '25,000', label: 'พื้นที่โรงงาน (ตร.ม.)' },
          { value: '25+', label: 'ปีแห่งความเชี่ยวชาญ' },
          { value: '99.98%', label: 'อัตรามาตรฐานผ่านการตรวจสอบ' },
        ],
      },
      payload: {},
    },
  ],
};

export const MOCK_NEWS: LocalizedNewsArticle[] = [
  {
    id: 'news-1',
    category: 'SUSTAINABILITY',
    language: 'th',
    title: 'โลหะกิจรุ่งเจริญทรัพย์ ติดตั้งระบบ Solar Rooftop ผลิตพลังงานสะอาดลดคาร์บอน 1,200 ตันต่อปี',
    slug: 'lohakit-solar-rooftop-green-initiative',
    summary: 'เดินหน้าสู่โรงงานสีเขียวด้วยการติดตั้งแผงโซลาร์เซลล์ขนาด 1.2 MW ช่วยขับเคลื่อนการผลิตด้วยพลังงานสะอาด 100%',
    contentBody: '<p>บริษัท โลหะกิจรุ่งเจริญทรัพย์ จำกัด ได้เสร็จสิ้นการติดตั้งระบบ Solar Rooftop ณ โรงงานจังหวัดสมุทรสาคร เพื่อมุ่งสู่ความเป็นกลางทางคาร์บอน...</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'news-2',
    category: 'TECHNOLOGY',
    language: 'th',
    title: 'เปิดตัวสายการผลิตกระป๋องอาหารความเร็วสูงรุ่นใหม่ นำเข้าจากสวิตเซอร์แลนด์',
    slug: 'new-high-speed-canmaking-line',
    summary: 'เพิ่มกำลังการผลิตอีก 30% พร้อมระบบ AI Visual Inspection ตรวจสอบคุณภาพตะเข็บแบบ Real-time',
    contentBody: '<p>เพื่อรองรับการเติบโตของอุตสาหกรรมอาหารส่งออก ทางบริษัทฯ ได้ลงทุนขยายสายการผลิตกระป๋อง 3 ชิ้น ความเร็ว 600 กระป๋องต่อนาที...</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2026-07-20T10:30:00Z',
  },
];

export const MOCK_MEDIA: MediaFile[] = [
  {
    id: 'med-1',
    filename: 'food-can-300.jpg',
    originalFilename: 'food-can-300.jpg',
    bucket: 'lohakit-media',
    storageKey: 'products/2026/09/food-can-300.jpg',
    mimeType: 'image/jpeg',
    fileSize: 485000,
    width: 1200,
    height: 800,
    hashSha256: 'a1b2c3d4e5f6',
    altText: { th: 'กระป๋องอาหาร 300', en: 'Food Can 300' },
    folder: 'products',
    url: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=80',
    uploaderName: 'Lohakit Admin',
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'med-2',
    filename: 'factory-exterior.jpg',
    originalFilename: 'factory-exterior.jpg',
    bucket: 'lohakit-media',
    storageKey: 'facility/2026/09/factory-exterior.jpg',
    mimeType: 'image/jpeg',
    fileSize: 890000,
    width: 1920,
    height: 1080,
    hashSha256: 'c7d8e9f0a1b2',
    altText: { th: 'โรงงานสมุทรสาคร', en: 'Factory Plant' },
    folder: 'facility',
    url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    uploaderName: 'Lohakit Admin',
    createdAt: '2026-08-28T14:30:00Z',
    updatedAt: '2026-08-28T14:30:00Z',
  },
];
