// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs a
WHERE ($1::text IS NULL OR a.resource = $1)
  AND ($2::text IS NULL OR a.action = $2)
  AND ($3::uuid IS NULL OR a.user_id = $3)
`

type CountAuditLogsParams struct {
	Resource pgtype.Text `json:"resource"`
	Action   pgtype.Text `json:"action"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.Resource, arg.Action, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, resource, resource_id, ip_address, user_agent, old_values, new_values)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, action, resource, resource_id, ip_address, user_agent, old_values, new_values, created_at
`

type CreateAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID string      `json:"resource_id"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.OldValues,
		arg.NewValues,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.OldValues,
		&i.NewValues,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, a.action, a.resource, a.resource_id, a.ip_address, a.user_agent, a.old_values, a.new_values, a.created_at, u.full_name as user_name, u.email as user_email
FROM audit_logs a
LEFT JOIN users u ON a.user_id = u.id
WHERE ($3::text IS NULL OR a.resource = $3)
  AND ($4::text IS NULL OR a.action = $4)
  AND ($5::uuid IS NULL OR a.user_id = $5)
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Resource pgtype.Text `json:"resource"`
	Action   pgtype.Text `json:"action"`
	UserID   pgtype.UUID `json:"user_id"`
}

type ListAuditLogsRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID string             `json:"resource_id"`
	IpAddress  string             `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	OldValues  []byte             `json:"old_values"`
	NewValues  []byte             `json:"new_values"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   pgtype.Text        `json:"user_name"`
	UserEmail  pgtype.Text        `json:"user_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.Resource,
		arg.Action,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.OldValues,
			&i.NewValues,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
