// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContactInquiries = `-- name: CountContactInquiries :one
SELECT COUNT(*) FROM contact_inquiries
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::boolean IS NULL OR is_spam = $2)
`

type CountContactInquiriesParams struct {
	Status pgtype.Text `json:"status"`
	IsSpam pgtype.Bool `json:"is_spam"`
}

func (q *Queries) CountContactInquiries(ctx context.Context, arg CountContactInquiriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContactInquiries, arg.Status, arg.IsSpam)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContactInquiry = `-- name: CreateContactInquiry :one
INSERT INTO contact_inquiries (name, company_name, email, phone, subject, message, interest_category, ip_address, user_agent, is_spam)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, company_name, email, phone, subject, message, interest_category, ip_address, user_agent, status, is_spam, created_at, updated_at, deleted_at
`

type CreateContactInquiryParams struct {
	Name             string      `json:"name"`
	CompanyName      pgtype.Text `json:"company_name"`
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Subject          string      `json:"subject"`
	Message          string      `json:"message"`
	InterestCategory string      `json:"interest_category"`
	IpAddress        string      `json:"ip_address"`
	UserAgent        pgtype.Text `json:"user_agent"`
	IsSpam           bool        `json:"is_spam"`
}

func (q *Queries) CreateContactInquiry(ctx context.Context, arg CreateContactInquiryParams) (ContactInquiry, error) {
	row := q.db.QueryRow(ctx, createContactInquiry,
		arg.Name,
		arg.CompanyName,
		arg.Email,
		arg.Phone,
		arg.Subject,
		arg.Message,
		arg.InterestCategory,
		arg.IpAddress,
		arg.UserAgent,
		arg.IsSpam,
	)
	var i ContactInquiry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompanyName,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.InterestCategory,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.IsSpam,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContactInquiryByID = `-- name: GetContactInquiryByID :one
SELECT id, name, company_name, email, phone, subject, message, interest_category, ip_address, user_agent, status, is_spam, created_at, updated_at, deleted_at FROM contact_inquiries WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContactInquiryByID(ctx context.Context, id uuid.UUID) (ContactInquiry, error) {
	row := q.db.QueryRow(ctx, getContactInquiryByID, id)
	var i ContactInquiry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompanyName,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.InterestCategory,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.IsSpam,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContactInquiries = `-- name: ListContactInquiries :many
SELECT id, name, company_name, email, phone, subject, message, interest_category, ip_address, user_agent, status, is_spam, created_at, updated_at, deleted_at FROM contact_inquiries
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3)
  AND ($4::boolean IS NULL OR is_spam = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListContactInquiriesParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	IsSpam pgtype.Bool `json:"is_spam"`
}

func (q *Queries) ListContactInquiries(ctx context.Context, arg ListContactInquiriesParams) ([]ContactInquiry, error) {
	rows, err := q.db.Query(ctx, listContactInquiries,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.IsSpam,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactInquiry
	for rows.Next() {
		var i ContactInquiry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompanyName,
			&i.Email,
			&i.Phone,
			&i.Subject,
			&i.Message,
			&i.InterestCategory,
			&i.IpAddress,
			&i.UserAgent,
			&i.Status,
			&i.IsSpam,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteContactInquiry = `-- name: PermanentDeleteContactInquiry :exec
DELETE FROM contact_inquiries WHERE id = $1
`

func (q *Queries) PermanentDeleteContactInquiry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeleteContactInquiry, id)
	return err
}

const softDeleteContactInquiry = `-- name: SoftDeleteContactInquiry :exec
UPDATE contact_inquiries
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteContactInquiry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteContactInquiry, id)
	return err
}

const updateContactInquiryStatus = `-- name: UpdateContactInquiryStatus :one
UPDATE contact_inquiries
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, company_name, email, phone, subject, message, interest_category, ip_address, user_agent, status, is_spam, created_at, updated_at, deleted_at
`

type UpdateContactInquiryStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateContactInquiryStatus(ctx context.Context, arg UpdateContactInquiryStatusParams) (ContactInquiry, error) {
	row := q.db.QueryRow(ctx, updateContactInquiryStatus, arg.ID, arg.Status)
	var i ContactInquiry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompanyName,
		&i.Email,
		&i.Phone,
		&i.Subject,
		&i.Message,
		&i.InterestCategory,
		&i.IpAddress,
		&i.UserAgent,
		&i.Status,
		&i.IsSpam,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
