// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaFiles = `-- name: CountMediaFiles :one
SELECT COUNT(*) FROM media_files m
WHERE m.deleted_at IS NULL
  AND ($1::text IS NULL OR m.folder = $1)
  AND ($2::text IS NULL OR m.mime_type ILIKE $2 || '%')
  AND ($3::text IS NULL OR m.filename ILIKE '%' || $3 || '%')
`

type CountMediaFilesParams struct {
	Folder   pgtype.Text `json:"folder"`
	MimeType pgtype.Text `json:"mime_type"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountMediaFiles(ctx context.Context, arg CountMediaFilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaFiles, arg.Folder, arg.MimeType, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (
    filename, original_filename, bucket, storage_key, mime_type, file_size, width, height, hash_sha256, alt_text, folder, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, filename, original_filename, bucket, storage_key, mime_type, file_size, width, height, hash_sha256, alt_text, folder, created_by, created_at, updated_at, deleted_at
`

type CreateMediaFileParams struct {
	Filename         string      `json:"filename"`
	OriginalFilename string      `json:"original_filename"`
	Bucket           string      `json:"bucket"`
	StorageKey       string      `json:"storage_key"`
	MimeType         string      `json:"mime_type"`
	FileSize         int64       `json:"file_size"`
	Width            pgtype.Int4 `json:"width"`
	Height           pgtype.Int4 `json:"height"`
	HashSha256       string      `json:"hash_sha256"`
	AltText          []byte      `json:"alt_text"`
	Folder           string      `json:"folder"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.Filename,
		arg.OriginalFilename,
		arg.Bucket,
		arg.StorageKey,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.HashSha256,
		arg.AltText,
		arg.Folder,
		arg.CreatedBy,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Bucket,
		&i.StorageKey,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.HashSha256,
		&i.AltText,
		&i.Folder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT m.id, m.filename, m.original_filename, m.bucket, m.storage_key, m.mime_type, m.file_size, m.width, m.height, m.hash_sha256, m.alt_text, m.folder, m.created_by, m.created_at, m.updated_at, m.deleted_at, u.full_name as uploader_name
FROM media_files m
LEFT JOIN users u ON m.created_by = u.id
WHERE m.id = $1 AND m.deleted_at IS NULL
`

type GetMediaByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	Filename         string             `json:"filename"`
	OriginalFilename string             `json:"original_filename"`
	Bucket           string             `json:"bucket"`
	StorageKey       string             `json:"storage_key"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	Width            pgtype.Int4        `json:"width"`
	Height           pgtype.Int4        `json:"height"`
	HashSha256       string             `json:"hash_sha256"`
	AltText          []byte             `json:"alt_text"`
	Folder           string             `json:"folder"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	UploaderName     pgtype.Text        `json:"uploader_name"`
}

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (GetMediaByIDRow, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i GetMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Bucket,
		&i.StorageKey,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.HashSha256,
		&i.AltText,
		&i.Folder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UploaderName,
	)
	return i, err
}

const getMediaByStorageKey = `-- name: GetMediaByStorageKey :one
SELECT id, filename, original_filename, bucket, storage_key, mime_type, file_size, width, height, hash_sha256, alt_text, folder, created_by, created_at, updated_at, deleted_at FROM media_files WHERE storage_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMediaByStorageKey(ctx context.Context, storageKey string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaByStorageKey, storageKey)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Bucket,
		&i.StorageKey,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.HashSha256,
		&i.AltText,
		&i.Folder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMediaFiles = `-- name: ListMediaFiles :many
SELECT m.id, m.filename, m.original_filename, m.bucket, m.storage_key, m.mime_type, m.file_size, m.width, m.height, m.hash_sha256, m.alt_text, m.folder, m.created_by, m.created_at, m.updated_at, m.deleted_at, u.full_name as uploader_name
FROM media_files m
LEFT JOIN users u ON m.created_by = u.id
WHERE m.deleted_at IS NULL
  AND ($3::text IS NULL OR m.folder = $3)
  AND ($4::text IS NULL OR m.mime_type ILIKE $4 || '%')
  AND ($5::text IS NULL OR m.filename ILIKE '%' || $5 || '%' OR m.original_filename ILIKE '%' || $5 || '%')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaFilesParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Folder   pgtype.Text `json:"folder"`
	MimeType pgtype.Text `json:"mime_type"`
	Search   pgtype.Text `json:"search"`
}

type ListMediaFilesRow struct {
	ID               uuid.UUID          `json:"id"`
	Filename         string             `json:"filename"`
	OriginalFilename string             `json:"original_filename"`
	Bucket           string             `json:"bucket"`
	StorageKey       string             `json:"storage_key"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	Width            pgtype.Int4        `json:"width"`
	Height           pgtype.Int4        `json:"height"`
	HashSha256       string             `json:"hash_sha256"`
	AltText          []byte             `json:"alt_text"`
	Folder           string             `json:"folder"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	UploaderName     pgtype.Text        `json:"uploader_name"`
}

func (q *Queries) ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]ListMediaFilesRow, error) {
	rows, err := q.db.Query(ctx, listMediaFiles,
		arg.Limit,
		arg.Offset,
		arg.Folder,
		arg.MimeType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaFilesRow
	for rows.Next() {
		var i ListMediaFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.Bucket,
			&i.StorageKey,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.HashSha256,
			&i.AltText,
			&i.Folder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteMedia = `-- name: PermanentDeleteMedia :exec
DELETE FROM media_files WHERE id = $1
`

func (q *Queries) PermanentDeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeleteMedia, id)
	return err
}

const replaceMediaFile = `-- name: ReplaceMediaFile :one
UPDATE media_files
SET original_filename = $2,
    mime_type = $3,
    file_size = $4,
    width = $5,
    height = $6,
    hash_sha256 = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, filename, original_filename, bucket, storage_key, mime_type, file_size, width, height, hash_sha256, alt_text, folder, created_by, created_at, updated_at, deleted_at
`

type ReplaceMediaFileParams struct {
	ID               uuid.UUID   `json:"id"`
	OriginalFilename string      `json:"original_filename"`
	MimeType         string      `json:"mime_type"`
	FileSize         int64       `json:"file_size"`
	Width            pgtype.Int4 `json:"width"`
	Height           pgtype.Int4 `json:"height"`
	HashSha256       string      `json:"hash_sha256"`
}

func (q *Queries) ReplaceMediaFile(ctx context.Context, arg ReplaceMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, replaceMediaFile,
		arg.ID,
		arg.OriginalFilename,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.HashSha256,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Bucket,
		&i.StorageKey,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.HashSha256,
		&i.AltText,
		&i.Folder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreMedia = `-- name: RestoreMedia :exec
UPDATE media_files
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreMedia, id)
	return err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media_files
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMedia, id)
	return err
}

const updateMediaMetadata = `-- name: UpdateMediaMetadata :one
UPDATE media_files
SET filename = $2, alt_text = $3, folder = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, filename, original_filename, bucket, storage_key, mime_type, file_size, width, height, hash_sha256, alt_text, folder, created_by, created_at, updated_at, deleted_at
`

type UpdateMediaMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Filename string    `json:"filename"`
	AltText  []byte    `json:"alt_text"`
	Folder   string    `json:"folder"`
}

func (q *Queries) UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, updateMediaMetadata,
		arg.ID,
		arg.Filename,
		arg.AltText,
		arg.Folder,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Bucket,
		&i.StorageKey,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.HashSha256,
		&i.AltText,
		&i.Folder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
