// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         uuid.UUID          `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID string             `json:"resource_id"`
	IpAddress  string             `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	OldValues  []byte             `json:"old_values"`
	NewValues  []byte             `json:"new_values"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ContactInquiry struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	CompanyName      pgtype.Text        `json:"company_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	Subject          string             `json:"subject"`
	Message          string             `json:"message"`
	InterestCategory string             `json:"interest_category"`
	IpAddress        string             `json:"ip_address"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Status           string             `json:"status"`
	IsSpam           bool               `json:"is_spam"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ContentRevision struct {
	ID            uuid.UUID          `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	VersionNumber int32              `json:"version_number"`
	Snapshot      []byte             `json:"snapshot"`
	ChangeSummary pgtype.Text        `json:"change_summary"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MediaFile struct {
	ID               uuid.UUID          `json:"id"`
	Filename         string             `json:"filename"`
	OriginalFilename string             `json:"original_filename"`
	Bucket           string             `json:"bucket"`
	StorageKey       string             `json:"storage_key"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	Width            pgtype.Int4        `json:"width"`
	Height           pgtype.Int4        `json:"height"`
	HashSha256       string             `json:"hash_sha256"`
	AltText          []byte             `json:"alt_text"`
	Folder           string             `json:"folder"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type NewsArticle struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	Category        string             `json:"category"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type NewsArticleTranslation struct {
	ID              uuid.UUID          `json:"id"`
	ArticleID       uuid.UUID          `json:"article_id"`
	LanguageCode    string             `json:"language_code"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Summary         pgtype.Text        `json:"summary"`
	ContentBody     string             `json:"content_body"`
	MetaTitle       pgtype.Text        `json:"meta_title"`
	MetaDescription pgtype.Text        `json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Page struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PageSection struct {
	ID          uuid.UUID          `json:"id"`
	PageID      uuid.UUID          `json:"page_id"`
	SectionType string             `json:"section_type"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PageSectionTranslation struct {
	ID           uuid.UUID          `json:"id"`
	SectionID    uuid.UUID          `json:"section_id"`
	LanguageCode string             `json:"language_code"`
	Title        pgtype.Text        `json:"title"`
	Subtitle     pgtype.Text        `json:"subtitle"`
	ContentBody  pgtype.Text        `json:"content_body"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PageTranslation struct {
	ID              uuid.UUID          `json:"id"`
	PageID          uuid.UUID          `json:"page_id"`
	LanguageCode    string             `json:"language_code"`
	Title           string             `json:"title"`
	MetaTitle       pgtype.Text        `json:"meta_title"`
	MetaDescription pgtype.Text        `json:"meta_description"`
	MetaKeywords    pgtype.Text        `json:"meta_keywords"`
	OgMetadata      []byte             `json:"og_metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Module      string             `json:"module"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID              uuid.UUID          `json:"id"`
	CategoryID      uuid.UUID          `json:"category_id"`
	Sku             string             `json:"sku"`
	Status          string             `json:"status"`
	Specifications  []byte             `json:"specifications"`
	SortOrder       int32              `json:"sort_order"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategory struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategoryTranslation struct {
	ID           uuid.UUID          `json:"id"`
	CategoryID   uuid.UUID          `json:"category_id"`
	LanguageCode string             `json:"language_code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID          `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	MediaID   uuid.UUID          `json:"media_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProductTranslation struct {
	ID              uuid.UUID          `json:"id"`
	ProductID       uuid.UUID          `json:"product_id"`
	LanguageCode    string             `json:"language_code"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     pgtype.Text        `json:"description"`
	Features        pgtype.Text        `json:"features"`
	Applications    pgtype.Text        `json:"applications"`
	Material        pgtype.Text        `json:"material"`
	CoatingType     pgtype.Text        `json:"coating_type"`
	MetaTitle       pgtype.Text        `json:"meta_title"`
	MetaDescription pgtype.Text        `json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID          `json:"role_id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	SessionToken      string             `json:"session_token"`
	CsrfToken         string             `json:"csrf_token"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ReauthenticatedAt pgtype.Timestamptz `json:"reauthenticated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SiteSetting struct {
	ID           uuid.UUID          `json:"id"`
	SettingGroup string             `json:"setting_group"`
	SettingKey   string             `json:"setting_key"`
	Value        []byte             `json:"value"`
	IsPublic     bool               `json:"is_public"`
	Description  pgtype.Text        `json:"description"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ThemeConfig struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	Tokens    []byte             `json:"tokens"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
