// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNewsArticles = `-- name: CountNewsArticles :one
SELECT COUNT(*) FROM news_articles n
WHERE n.deleted_at IS NULL
  AND ($1::text IS NULL OR n.status = $1)
  AND ($2::text IS NULL OR n.category = $2)
`

type CountNewsArticlesParams struct {
	Status   pgtype.Text `json:"status"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) CountNewsArticles(ctx context.Context, arg CountNewsArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsArticles, arg.Status, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNewsArticle = `-- name: CreateNewsArticle :one
INSERT INTO news_articles (status, published_at, featured_image_id, category, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, status, published_at, featured_image_id, category, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateNewsArticleParams struct {
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	Category        string             `json:"category"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateNewsArticle(ctx context.Context, arg CreateNewsArticleParams) (NewsArticle, error) {
	row := q.db.QueryRow(ctx, createNewsArticle,
		arg.Status,
		arg.PublishedAt,
		arg.FeaturedImageID,
		arg.Category,
		arg.CreatedBy,
	)
	var i NewsArticle
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PublishedAt,
		&i.FeaturedImageID,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNewsArticleByID = `-- name: GetNewsArticleByID :one
SELECT n.id, n.status, n.published_at, n.featured_image_id, n.category, n.created_by, n.updated_by, n.created_at, n.updated_at, n.deleted_at, m.storage_key as featured_image_key
FROM news_articles n
LEFT JOIN media_files m ON n.featured_image_id = m.id
WHERE n.id = $1 AND n.deleted_at IS NULL
`

type GetNewsArticleByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	FeaturedImageID  pgtype.UUID        `json:"featured_image_id"`
	Category         string             `json:"category"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) GetNewsArticleByID(ctx context.Context, id uuid.UUID) (GetNewsArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getNewsArticleByID, id)
	var i GetNewsArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PublishedAt,
		&i.FeaturedImageID,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FeaturedImageKey,
	)
	return i, err
}

const getNewsTranslationBySlugAndLang = `-- name: GetNewsTranslationBySlugAndLang :one
SELECT nt.id, nt.article_id, nt.language_code, nt.title, nt.slug, nt.summary, nt.content_body, nt.meta_title, nt.meta_description, nt.created_at, nt.updated_at, n.id as article_id, n.status, n.published_at, n.category, m.storage_key as featured_image_key
FROM news_article_translations nt
JOIN news_articles n ON nt.article_id = n.id
LEFT JOIN media_files m ON n.featured_image_id = m.id
WHERE nt.slug = $1 AND nt.language_code = $2 AND n.deleted_at IS NULL AND n.status = 'PUBLISHED'
`

type GetNewsTranslationBySlugAndLangParams struct {
	Slug         string `json:"slug"`
	LanguageCode string `json:"language_code"`
}

type GetNewsTranslationBySlugAndLangRow struct {
	ID               uuid.UUID          `json:"id"`
	ArticleID        uuid.UUID          `json:"article_id"`
	LanguageCode     string             `json:"language_code"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Summary          pgtype.Text        `json:"summary"`
	ContentBody      string             `json:"content_body"`
	MetaTitle        pgtype.Text        `json:"meta_title"`
	MetaDescription  pgtype.Text        `json:"meta_description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ArticleID_2      uuid.UUID          `json:"article_id_2"`
	Status           string             `json:"status"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	Category         string             `json:"category"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) GetNewsTranslationBySlugAndLang(ctx context.Context, arg GetNewsTranslationBySlugAndLangParams) (GetNewsTranslationBySlugAndLangRow, error) {
	row := q.db.QueryRow(ctx, getNewsTranslationBySlugAndLang, arg.Slug, arg.LanguageCode)
	var i GetNewsTranslationBySlugAndLangRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.LanguageCode,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleID_2,
		&i.Status,
		&i.PublishedAt,
		&i.Category,
		&i.FeaturedImageKey,
	)
	return i, err
}

const getNewsTranslations = `-- name: GetNewsTranslations :many
SELECT id, article_id, language_code, title, slug, summary, content_body, meta_title, meta_description, created_at, updated_at FROM news_article_translations WHERE article_id = $1
`

func (q *Queries) GetNewsTranslations(ctx context.Context, articleID uuid.UUID) ([]NewsArticleTranslation, error) {
	rows, err := q.db.Query(ctx, getNewsTranslations, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsArticleTranslation
	for rows.Next() {
		var i NewsArticleTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.LanguageCode,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.ContentBody,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsArticles = `-- name: ListNewsArticles :many
SELECT n.id, n.status, n.published_at, n.featured_image_id, n.category, n.created_by, n.updated_by, n.created_at, n.updated_at, n.deleted_at, m.storage_key as featured_image_key
FROM news_articles n
LEFT JOIN media_files m ON n.featured_image_id = m.id
WHERE n.deleted_at IS NULL
  AND ($3::text IS NULL OR n.status = $3)
  AND ($4::text IS NULL OR n.category = $4)
ORDER BY n.created_at DESC
LIMIT $1 OFFSET $2
`

type ListNewsArticlesParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	Category pgtype.Text `json:"category"`
}

type ListNewsArticlesRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	FeaturedImageID  pgtype.UUID        `json:"featured_image_id"`
	Category         string             `json:"category"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) ListNewsArticles(ctx context.Context, arg ListNewsArticlesParams) ([]ListNewsArticlesRow, error) {
	rows, err := q.db.Query(ctx, listNewsArticles,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsArticlesRow
	for rows.Next() {
		var i ListNewsArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PublishedAt,
			&i.FeaturedImageID,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FeaturedImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteNewsArticle = `-- name: PermanentDeleteNewsArticle :exec
DELETE FROM news_articles WHERE id = $1
`

func (q *Queries) PermanentDeleteNewsArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeleteNewsArticle, id)
	return err
}

const restoreNewsArticle = `-- name: RestoreNewsArticle :exec
UPDATE news_articles
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreNewsArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreNewsArticle, id)
	return err
}

const softDeleteNewsArticle = `-- name: SoftDeleteNewsArticle :exec
UPDATE news_articles
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNewsArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteNewsArticle, id)
	return err
}

const updateNewsArticle = `-- name: UpdateNewsArticle :one
UPDATE news_articles
SET status = $2,
    published_at = CASE WHEN $2 = 'PUBLISHED' AND published_at IS NULL THEN NOW() ELSE published_at END,
    featured_image_id = $3,
    category = $4,
    updated_by = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status, published_at, featured_image_id, category, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateNewsArticleParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	FeaturedImageID pgtype.UUID `json:"featured_image_id"`
	Category        string      `json:"category"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateNewsArticle(ctx context.Context, arg UpdateNewsArticleParams) (NewsArticle, error) {
	row := q.db.QueryRow(ctx, updateNewsArticle,
		arg.ID,
		arg.Status,
		arg.FeaturedImageID,
		arg.Category,
		arg.UpdatedBy,
	)
	var i NewsArticle
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PublishedAt,
		&i.FeaturedImageID,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertNewsTranslation = `-- name: UpsertNewsTranslation :one
INSERT INTO news_article_translations (article_id, language_code, title, slug, summary, content_body, meta_title, meta_description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (article_id, language_code) DO UPDATE
SET title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    summary = EXCLUDED.summary,
    content_body = EXCLUDED.content_body,
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    updated_at = NOW()
RETURNING id, article_id, language_code, title, slug, summary, content_body, meta_title, meta_description, created_at, updated_at
`

type UpsertNewsTranslationParams struct {
	ArticleID       uuid.UUID   `json:"article_id"`
	LanguageCode    string      `json:"language_code"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Summary         pgtype.Text `json:"summary"`
	ContentBody     string      `json:"content_body"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
}

func (q *Queries) UpsertNewsTranslation(ctx context.Context, arg UpsertNewsTranslationParams) (NewsArticleTranslation, error) {
	row := q.db.QueryRow(ctx, upsertNewsTranslation,
		arg.ArticleID,
		arg.LanguageCode,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.ContentBody,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i NewsArticleTranslation
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.LanguageCode,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentBody,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
