// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR slug ILIKE '%' || $2 || '%')
`

type CountPagesParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountPages(ctx context.Context, arg CountPagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPages, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContentRevision = `-- name: CreateContentRevision :one
INSERT INTO content_revisions (entity_type, entity_id, version_number, snapshot, change_summary, created_by)
VALUES (
    $1, 
    $2, 
    COALESCE((SELECT MAX(version_number) + 1 FROM content_revisions WHERE entity_type = $1 AND entity_id = $2), 1),
    $3, 
    $4, 
    $5
)
RETURNING id, entity_type, entity_id, version_number, snapshot, change_summary, created_by, created_at
`

type CreateContentRevisionParams struct {
	EntityType    string      `json:"entity_type"`
	EntityID      uuid.UUID   `json:"entity_id"`
	Snapshot      []byte      `json:"snapshot"`
	ChangeSummary pgtype.Text `json:"change_summary"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateContentRevision(ctx context.Context, arg CreateContentRevisionParams) (ContentRevision, error) {
	row := q.db.QueryRow(ctx, createContentRevision,
		arg.EntityType,
		arg.EntityID,
		arg.Snapshot,
		arg.ChangeSummary,
		arg.CreatedBy,
	)
	var i ContentRevision
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNumber,
		&i.Snapshot,
		&i.ChangeSummary,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (slug, status, created_by, updated_by)
VALUES ($1, $2, $3, $3)
RETURNING id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreatePageParams struct {
	Slug      string      `json:"slug"`
	Status    string      `json:"status"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage, arg.Slug, arg.Status, arg.CreatedBy)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPageSection = `-- name: CreatePageSection :one
INSERT INTO page_sections (page_id, section_type, sort_order, is_active, config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, page_id, section_type, sort_order, is_active, config, created_at, updated_at, deleted_at
`

type CreatePageSectionParams struct {
	PageID      uuid.UUID `json:"page_id"`
	SectionType string    `json:"section_type"`
	SortOrder   int32     `json:"sort_order"`
	IsActive    bool      `json:"is_active"`
	Config      []byte    `json:"config"`
}

func (q *Queries) CreatePageSection(ctx context.Context, arg CreatePageSectionParams) (PageSection, error) {
	row := q.db.QueryRow(ctx, createPageSection,
		arg.PageID,
		arg.SectionType,
		arg.SortOrder,
		arg.IsActive,
		arg.Config,
	)
	var i PageSection
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SectionType,
		&i.SortOrder,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContentRevisionByID = `-- name: GetContentRevisionByID :one
SELECT id, entity_type, entity_id, version_number, snapshot, change_summary, created_by, created_at FROM content_revisions WHERE id = $1
`

func (q *Queries) GetContentRevisionByID(ctx context.Context, id uuid.UUID) (ContentRevision, error) {
	row := q.db.QueryRow(ctx, getContentRevisionByID, id)
	var i ContentRevision
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.VersionNumber,
		&i.Snapshot,
		&i.ChangeSummary,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at FROM pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageByID(ctx context.Context, id uuid.UUID) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at FROM pages WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageSectionByID = `-- name: GetPageSectionByID :one
SELECT id, page_id, section_type, sort_order, is_active, config, created_at, updated_at, deleted_at FROM page_sections WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageSectionByID(ctx context.Context, id uuid.UUID) (PageSection, error) {
	row := q.db.QueryRow(ctx, getPageSectionByID, id)
	var i PageSection
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SectionType,
		&i.SortOrder,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageTranslationByLang = `-- name: GetPageTranslationByLang :one
SELECT id, page_id, language_code, title, meta_title, meta_description, meta_keywords, og_metadata, created_at, updated_at FROM page_translations WHERE page_id = $1 AND language_code = $2
`

type GetPageTranslationByLangParams struct {
	PageID       uuid.UUID `json:"page_id"`
	LanguageCode string    `json:"language_code"`
}

func (q *Queries) GetPageTranslationByLang(ctx context.Context, arg GetPageTranslationByLangParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, getPageTranslationByLang, arg.PageID, arg.LanguageCode)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LanguageCode,
		&i.Title,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageTranslations = `-- name: GetPageTranslations :many
SELECT id, page_id, language_code, title, meta_title, meta_description, meta_keywords, og_metadata, created_at, updated_at FROM page_translations WHERE page_id = $1
`

func (q *Queries) GetPageTranslations(ctx context.Context, pageID uuid.UUID) ([]PageTranslation, error) {
	rows, err := q.db.Query(ctx, getPageTranslations, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageTranslation
	for rows.Next() {
		var i PageTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.LanguageCode,
			&i.Title,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedPageBySlug = `-- name: GetPublishedPageBySlug :one
SELECT id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at FROM pages WHERE slug = $1 AND status = 'PUBLISHED' AND deleted_at IS NULL
`

func (q *Queries) GetPublishedPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPublishedPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSectionTranslations = `-- name: GetSectionTranslations :many
SELECT id, section_id, language_code, title, subtitle, content_body, payload, created_at, updated_at FROM page_section_translations WHERE section_id = $1
`

func (q *Queries) GetSectionTranslations(ctx context.Context, sectionID uuid.UUID) ([]PageSectionTranslation, error) {
	rows, err := q.db.Query(ctx, getSectionTranslations, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSectionTranslation
	for rows.Next() {
		var i PageSectionTranslation
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.LanguageCode,
			&i.Title,
			&i.Subtitle,
			&i.ContentBody,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePageSections = `-- name: ListActivePageSections :many
SELECT id, page_id, section_type, sort_order, is_active, config, created_at, updated_at, deleted_at FROM page_sections
WHERE page_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) ListActivePageSections(ctx context.Context, pageID uuid.UUID) ([]PageSection, error) {
	rows, err := q.db.Query(ctx, listActivePageSections, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSection
	for rows.Next() {
		var i PageSection
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.SectionType,
			&i.SortOrder,
			&i.IsActive,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentRevisions = `-- name: ListContentRevisions :many
SELECT r.id, r.entity_type, r.entity_id, r.version_number, r.snapshot, r.change_summary, r.created_by, r.created_at, u.full_name as author_name, u.email as author_email
FROM content_revisions r
LEFT JOIN users u ON r.created_by = u.id
WHERE r.entity_type = $1 AND r.entity_id = $2
ORDER BY r.version_number DESC
`

type ListContentRevisionsParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

type ListContentRevisionsRow struct {
	ID            uuid.UUID          `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	VersionNumber int32              `json:"version_number"`
	Snapshot      []byte             `json:"snapshot"`
	ChangeSummary pgtype.Text        `json:"change_summary"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AuthorName    pgtype.Text        `json:"author_name"`
	AuthorEmail   pgtype.Text        `json:"author_email"`
}

func (q *Queries) ListContentRevisions(ctx context.Context, arg ListContentRevisionsParams) ([]ListContentRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listContentRevisions, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentRevisionsRow
	for rows.Next() {
		var i ListContentRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.VersionNumber,
			&i.Snapshot,
			&i.ChangeSummary,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSections = `-- name: ListPageSections :many
SELECT id, page_id, section_type, sort_order, is_active, config, created_at, updated_at, deleted_at FROM page_sections
WHERE page_id = $1 AND deleted_at IS NULL
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListPageSections(ctx context.Context, pageID uuid.UUID) ([]PageSection, error) {
	rows, err := q.db.Query(ctx, listPageSections, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSection
	for rows.Next() {
		var i PageSection
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.SectionType,
			&i.SortOrder,
			&i.IsActive,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPages = `-- name: ListPages :many
SELECT id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at FROM pages
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR slug ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPagesParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeletePage = `-- name: PermanentDeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) PermanentDeletePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeletePage, id)
	return err
}

const restorePage = `-- name: RestorePage :exec
UPDATE pages
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestorePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restorePage, id)
	return err
}

const setPageStatus = `-- name: SetPageStatus :one
UPDATE pages
SET status = $2, 
    published_at = CASE WHEN $2 = 'PUBLISHED' THEN NOW() ELSE published_at END,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at
`

type SetPageStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	Status    string      `json:"status"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetPageStatus(ctx context.Context, arg SetPageStatusParams) (Page, error) {
	row := q.db.QueryRow(ctx, setPageStatus, arg.ID, arg.Status, arg.UpdatedBy)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePage = `-- name: SoftDeletePage :exec
UPDATE pages
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePage, id)
	return err
}

const softDeletePageSection = `-- name: SoftDeletePageSection :exec
UPDATE page_sections
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePageSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePageSection, id)
	return err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET slug = $2, updated_by = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, slug, status, published_at, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdatePageParams struct {
	ID        uuid.UUID   `json:"id"`
	Slug      string      `json:"slug"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage, arg.ID, arg.Slug, arg.UpdatedBy)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePageSection = `-- name: UpdatePageSection :one
UPDATE page_sections
SET section_type = $2, sort_order = $3, is_active = $4, config = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, page_id, section_type, sort_order, is_active, config, created_at, updated_at, deleted_at
`

type UpdatePageSectionParams struct {
	ID          uuid.UUID `json:"id"`
	SectionType string    `json:"section_type"`
	SortOrder   int32     `json:"sort_order"`
	IsActive    bool      `json:"is_active"`
	Config      []byte    `json:"config"`
}

func (q *Queries) UpdatePageSection(ctx context.Context, arg UpdatePageSectionParams) (PageSection, error) {
	row := q.db.QueryRow(ctx, updatePageSection,
		arg.ID,
		arg.SectionType,
		arg.SortOrder,
		arg.IsActive,
		arg.Config,
	)
	var i PageSection
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SectionType,
		&i.SortOrder,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSectionSortOrder = `-- name: UpdateSectionSortOrder :exec
UPDATE page_sections
SET sort_order = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateSectionSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateSectionSortOrder(ctx context.Context, arg UpdateSectionSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateSectionSortOrder, arg.ID, arg.SortOrder)
	return err
}

const upsertPageSectionTranslation = `-- name: UpsertPageSectionTranslation :one
INSERT INTO page_section_translations (section_id, language_code, title, subtitle, content_body, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (section_id, language_code) DO UPDATE
SET title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    content_body = EXCLUDED.content_body,
    payload = EXCLUDED.payload,
    updated_at = NOW()
RETURNING id, section_id, language_code, title, subtitle, content_body, payload, created_at, updated_at
`

type UpsertPageSectionTranslationParams struct {
	SectionID    uuid.UUID   `json:"section_id"`
	LanguageCode string      `json:"language_code"`
	Title        pgtype.Text `json:"title"`
	Subtitle     pgtype.Text `json:"subtitle"`
	ContentBody  pgtype.Text `json:"content_body"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) UpsertPageSectionTranslation(ctx context.Context, arg UpsertPageSectionTranslationParams) (PageSectionTranslation, error) {
	row := q.db.QueryRow(ctx, upsertPageSectionTranslation,
		arg.SectionID,
		arg.LanguageCode,
		arg.Title,
		arg.Subtitle,
		arg.ContentBody,
		arg.Payload,
	)
	var i PageSectionTranslation
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.LanguageCode,
		&i.Title,
		&i.Subtitle,
		&i.ContentBody,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPageTranslation = `-- name: UpsertPageTranslation :one
INSERT INTO page_translations (page_id, language_code, title, meta_title, meta_description, meta_keywords, og_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (page_id, language_code) DO UPDATE
SET title = EXCLUDED.title,
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    meta_keywords = EXCLUDED.meta_keywords,
    og_metadata = EXCLUDED.og_metadata,
    updated_at = NOW()
RETURNING id, page_id, language_code, title, meta_title, meta_description, meta_keywords, og_metadata, created_at, updated_at
`

type UpsertPageTranslationParams struct {
	PageID          uuid.UUID   `json:"page_id"`
	LanguageCode    string      `json:"language_code"`
	Title           string      `json:"title"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	MetaKeywords    pgtype.Text `json:"meta_keywords"`
	OgMetadata      []byte      `json:"og_metadata"`
}

func (q *Queries) UpsertPageTranslation(ctx context.Context, arg UpsertPageTranslationParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, upsertPageTranslation,
		arg.PageID,
		arg.LanguageCode,
		arg.Title,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OgMetadata,
	)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.LanguageCode,
		&i.Title,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
