// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product_images (product_id, media_id, sort_order)
VALUES ($1, $2, $3)
RETURNING id, product_id, media_id, sort_order, created_at
`

type AddProductImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	MediaID   uuid.UUID `json:"media_id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, addProductImage, arg.ProductID, arg.MediaID, arg.SortOrder)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.MediaID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products p
WHERE p.deleted_at IS NULL
  AND ($1::uuid IS NULL OR p.category_id = $1)
  AND ($2::text IS NULL OR p.status = $2)
  AND ($3::text IS NULL OR p.sku ILIKE '%' || $3 || '%')
`

type CountProductsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Status     pgtype.Text `json:"status"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, sku, status, specifications, sort_order, featured_image_id, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, category_id, sku, status, specifications, sort_order, featured_image_id, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CategoryID      uuid.UUID   `json:"category_id"`
	Sku             string      `json:"sku"`
	Status          string      `json:"status"`
	Specifications  []byte      `json:"specifications"`
	SortOrder       int32       `json:"sort_order"`
	FeaturedImageID pgtype.UUID `json:"featured_image_id"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Sku,
		arg.Status,
		arg.Specifications,
		arg.SortOrder,
		arg.FeaturedImageID,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Status,
		&i.Specifications,
		&i.SortOrder,
		&i.FeaturedImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO product_categories (slug, sort_order, is_active)
VALUES ($1, $2, $3)
RETURNING id, slug, sort_order, is_active, created_at, updated_at, deleted_at
`

type CreateProductCategoryParams struct {
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory, arg.Slug, arg.SortOrder, arg.IsActive)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImages, productID)
	return err
}

const getCategoryTranslations = `-- name: GetCategoryTranslations :many
SELECT id, category_id, language_code, name, description, created_at, updated_at FROM product_category_translations WHERE category_id = $1
`

func (q *Queries) GetCategoryTranslations(ctx context.Context, categoryID uuid.UUID) ([]ProductCategoryTranslation, error) {
	rows, err := q.db.Query(ctx, getCategoryTranslations, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategoryTranslation
	for rows.Next() {
		var i ProductCategoryTranslation
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.category_id, p.sku, p.status, p.specifications, p.sort_order, p.featured_image_id, p.created_by, p.updated_by, p.created_at, p.updated_at, p.deleted_at, c.slug as category_slug, m.storage_key as featured_image_key
FROM products p
JOIN product_categories c ON p.category_id = c.id
LEFT JOIN media_files m ON p.featured_image_id = m.id
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	Sku              string             `json:"sku"`
	Status           string             `json:"status"`
	Specifications   []byte             `json:"specifications"`
	SortOrder        int32              `json:"sort_order"`
	FeaturedImageID  pgtype.UUID        `json:"featured_image_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CategorySlug     string             `json:"category_slug"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Status,
		&i.Specifications,
		&i.SortOrder,
		&i.FeaturedImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategorySlug,
		&i.FeaturedImageKey,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, category_id, sku, status, specifications, sort_order, featured_image_id, created_by, updated_by, created_at, updated_at, deleted_at FROM products WHERE sku = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Status,
		&i.Specifications,
		&i.SortOrder,
		&i.FeaturedImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductCategoryByID = `-- name: GetProductCategoryByID :one
SELECT id, slug, sort_order, is_active, created_at, updated_at, deleted_at FROM product_categories WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductCategoryByID(ctx context.Context, id uuid.UUID) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getProductCategoryByID, id)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductCategoryBySlug = `-- name: GetProductCategoryBySlug :one
SELECT id, slug, sort_order, is_active, created_at, updated_at, deleted_at FROM product_categories WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductCategoryBySlug(ctx context.Context, slug string) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getProductCategoryBySlug, slug)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT pi.id, pi.product_id, pi.media_id, pi.sort_order, pi.created_at, m.filename, m.storage_key, m.mime_type, m.alt_text
FROM product_images pi
JOIN media_files m ON pi.media_id = m.id
WHERE pi.product_id = $1 AND m.deleted_at IS NULL
ORDER BY pi.sort_order ASC
`

type GetProductImagesRow struct {
	ID         uuid.UUID          `json:"id"`
	ProductID  uuid.UUID          `json:"product_id"`
	MediaID    uuid.UUID          `json:"media_id"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Filename   string             `json:"filename"`
	StorageKey string             `json:"storage_key"`
	MimeType   string             `json:"mime_type"`
	AltText    []byte             `json:"alt_text"`
}

func (q *Queries) GetProductImages(ctx context.Context, productID uuid.UUID) ([]GetProductImagesRow, error) {
	rows, err := q.db.Query(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductImagesRow
	for rows.Next() {
		var i GetProductImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.MediaID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.Filename,
			&i.StorageKey,
			&i.MimeType,
			&i.AltText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTranslationBySlugAndLang = `-- name: GetProductTranslationBySlugAndLang :one
SELECT pt.id, pt.product_id, pt.language_code, pt.name, pt.slug, pt.description, pt.features, pt.applications, pt.material, pt.coating_type, pt.meta_title, pt.meta_description, pt.created_at, pt.updated_at, p.id as product_id, p.sku, p.category_id, p.specifications, p.status, m.storage_key as featured_image_key
FROM product_translations pt
JOIN products p ON pt.product_id = p.id
LEFT JOIN media_files m ON p.featured_image_id = m.id
WHERE pt.slug = $1 AND pt.language_code = $2 AND p.deleted_at IS NULL AND p.status = 'PUBLISHED'
`

type GetProductTranslationBySlugAndLangParams struct {
	Slug         string `json:"slug"`
	LanguageCode string `json:"language_code"`
}

type GetProductTranslationBySlugAndLangRow struct {
	ID               uuid.UUID          `json:"id"`
	ProductID        uuid.UUID          `json:"product_id"`
	LanguageCode     string             `json:"language_code"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Description      pgtype.Text        `json:"description"`
	Features         pgtype.Text        `json:"features"`
	Applications     pgtype.Text        `json:"applications"`
	Material         pgtype.Text        `json:"material"`
	CoatingType      pgtype.Text        `json:"coating_type"`
	MetaTitle        pgtype.Text        `json:"meta_title"`
	MetaDescription  pgtype.Text        `json:"meta_description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProductID_2      uuid.UUID          `json:"product_id_2"`
	Sku              string             `json:"sku"`
	CategoryID       uuid.UUID          `json:"category_id"`
	Specifications   []byte             `json:"specifications"`
	Status           string             `json:"status"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) GetProductTranslationBySlugAndLang(ctx context.Context, arg GetProductTranslationBySlugAndLangParams) (GetProductTranslationBySlugAndLangRow, error) {
	row := q.db.QueryRow(ctx, getProductTranslationBySlugAndLang, arg.Slug, arg.LanguageCode)
	var i GetProductTranslationBySlugAndLangRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LanguageCode,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Features,
		&i.Applications,
		&i.Material,
		&i.CoatingType,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID_2,
		&i.Sku,
		&i.CategoryID,
		&i.Specifications,
		&i.Status,
		&i.FeaturedImageKey,
	)
	return i, err
}

const getProductTranslations = `-- name: GetProductTranslations :many
SELECT id, product_id, language_code, name, slug, description, features, applications, material, coating_type, meta_title, meta_description, created_at, updated_at FROM product_translations WHERE product_id = $1
`

func (q *Queries) GetProductTranslations(ctx context.Context, productID uuid.UUID) ([]ProductTranslation, error) {
	rows, err := q.db.Query(ctx, getProductTranslations, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTranslation
	for rows.Next() {
		var i ProductTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.LanguageCode,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Features,
			&i.Applications,
			&i.Material,
			&i.CoatingType,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategories = `-- name: ListProductCategories :many
SELECT id, slug, sort_order, is_active, created_at, updated_at, deleted_at FROM product_categories
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProductCategories(ctx context.Context) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.category_id, p.sku, p.status, p.specifications, p.sort_order, p.featured_image_id, p.created_by, p.updated_by, p.created_at, p.updated_at, p.deleted_at, c.slug as category_slug, m.storage_key as featured_image_key
FROM products p
JOIN product_categories c ON p.category_id = c.id
LEFT JOIN media_files m ON p.featured_image_id = m.id
WHERE p.deleted_at IS NULL
  AND ($3::uuid IS NULL OR p.category_id = $3)
  AND ($4::text IS NULL OR p.status = $4)
  AND ($5::text IS NULL OR p.sku ILIKE '%' || $5 || '%')
ORDER BY p.sort_order ASC, p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID pgtype.UUID `json:"category_id"`
	Status     pgtype.Text `json:"status"`
	Search     pgtype.Text `json:"search"`
}

type ListProductsRow struct {
	ID               uuid.UUID          `json:"id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	Sku              string             `json:"sku"`
	Status           string             `json:"status"`
	Specifications   []byte             `json:"specifications"`
	SortOrder        int32              `json:"sort_order"`
	FeaturedImageID  pgtype.UUID        `json:"featured_image_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CategorySlug     string             `json:"category_slug"`
	FeaturedImageKey pgtype.Text        `json:"featured_image_key"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Sku,
			&i.Status,
			&i.Specifications,
			&i.SortOrder,
			&i.FeaturedImageID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategorySlug,
			&i.FeaturedImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteProduct = `-- name: PermanentDeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) PermanentDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeleteProduct, id)
	return err
}

const restoreProduct = `-- name: RestoreProduct :exec
UPDATE products
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreProduct, id)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const softDeleteProductCategory = `-- name: SoftDeleteProductCategory :exec
UPDATE product_categories
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProductCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProductCategory, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2,
    sku = $3,
    status = $4,
    specifications = $5,
    sort_order = $6,
    featured_image_id = $7,
    updated_by = $8,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, sku, status, specifications, sort_order, featured_image_id, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID              uuid.UUID   `json:"id"`
	CategoryID      uuid.UUID   `json:"category_id"`
	Sku             string      `json:"sku"`
	Status          string      `json:"status"`
	Specifications  []byte      `json:"specifications"`
	SortOrder       int32       `json:"sort_order"`
	FeaturedImageID pgtype.UUID `json:"featured_image_id"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Sku,
		arg.Status,
		arg.Specifications,
		arg.SortOrder,
		arg.FeaturedImageID,
		arg.UpdatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Status,
		&i.Specifications,
		&i.SortOrder,
		&i.FeaturedImageID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductCategory = `-- name: UpdateProductCategory :one
UPDATE product_categories
SET slug = $2, sort_order = $3, is_active = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, slug, sort_order, is_active, created_at, updated_at, deleted_at
`

type UpdateProductCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
}

func (q *Queries) UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, updateProductCategory,
		arg.ID,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertProductCategoryTranslation = `-- name: UpsertProductCategoryTranslation :one
INSERT INTO product_category_translations (category_id, language_code, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category_id, language_code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = NOW()
RETURNING id, category_id, language_code, name, description, created_at, updated_at
`

type UpsertProductCategoryTranslationParams struct {
	CategoryID   uuid.UUID   `json:"category_id"`
	LanguageCode string      `json:"language_code"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) UpsertProductCategoryTranslation(ctx context.Context, arg UpsertProductCategoryTranslationParams) (ProductCategoryTranslation, error) {
	row := q.db.QueryRow(ctx, upsertProductCategoryTranslation,
		arg.CategoryID,
		arg.LanguageCode,
		arg.Name,
		arg.Description,
	)
	var i ProductCategoryTranslation
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LanguageCode,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductTranslation = `-- name: UpsertProductTranslation :one
INSERT INTO product_translations (
    product_id, language_code, name, slug, description, features, applications, material, coating_type, meta_title, meta_description
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (product_id, language_code) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    features = EXCLUDED.features,
    applications = EXCLUDED.applications,
    material = EXCLUDED.material,
    coating_type = EXCLUDED.coating_type,
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    updated_at = NOW()
RETURNING id, product_id, language_code, name, slug, description, features, applications, material, coating_type, meta_title, meta_description, created_at, updated_at
`

type UpsertProductTranslationParams struct {
	ProductID       uuid.UUID   `json:"product_id"`
	LanguageCode    string      `json:"language_code"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	Description     pgtype.Text `json:"description"`
	Features        pgtype.Text `json:"features"`
	Applications    pgtype.Text `json:"applications"`
	Material        pgtype.Text `json:"material"`
	CoatingType     pgtype.Text `json:"coating_type"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
}

func (q *Queries) UpsertProductTranslation(ctx context.Context, arg UpsertProductTranslationParams) (ProductTranslation, error) {
	row := q.db.QueryRow(ctx, upsertProductTranslation,
		arg.ProductID,
		arg.LanguageCode,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Features,
		arg.Applications,
		arg.Material,
		arg.CoatingType,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i ProductTranslation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LanguageCode,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Features,
		&i.Applications,
		&i.Material,
		&i.CoatingType,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
