// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error)
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CleanupExpiredSessions(ctx context.Context) error
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	ClearUserRoles(ctx context.Context, userID uuid.UUID) error
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountContactInquiries(ctx context.Context, arg CountContactInquiriesParams) (int64, error)
	CountMediaFiles(ctx context.Context, arg CountMediaFilesParams) (int64, error)
	CountNewsArticles(ctx context.Context, arg CountNewsArticlesParams) (int64, error)
	CountPages(ctx context.Context, arg CountPagesParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountUsers(ctx context.Context, search pgtype.Text) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateContactInquiry(ctx context.Context, arg CreateContactInquiryParams) (ContactInquiry, error)
	CreateContentRevision(ctx context.Context, arg CreateContentRevisionParams) (ContentRevision, error)
	CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error)
	CreateNewsArticle(ctx context.Context, arg CreateNewsArticleParams) (NewsArticle, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePageSection(ctx context.Context, arg CreatePageSectionParams) (PageSection, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProductImages(ctx context.Context, productID uuid.UUID) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetActiveThemeConfig(ctx context.Context) (ThemeConfig, error)
	GetCategoryTranslations(ctx context.Context, categoryID uuid.UUID) ([]ProductCategoryTranslation, error)
	GetContactInquiryByID(ctx context.Context, id uuid.UUID) (ContactInquiry, error)
	GetContentRevisionByID(ctx context.Context, id uuid.UUID) (ContentRevision, error)
	GetMediaByID(ctx context.Context, id uuid.UUID) (GetMediaByIDRow, error)
	GetMediaByStorageKey(ctx context.Context, storageKey string) (MediaFile, error)
	GetNewsArticleByID(ctx context.Context, id uuid.UUID) (GetNewsArticleByIDRow, error)
	GetNewsTranslationBySlugAndLang(ctx context.Context, arg GetNewsTranslationBySlugAndLangParams) (GetNewsTranslationBySlugAndLangRow, error)
	GetNewsTranslations(ctx context.Context, articleID uuid.UUID) ([]NewsArticleTranslation, error)
	GetPageByID(ctx context.Context, id uuid.UUID) (Page, error)
	GetPageBySlug(ctx context.Context, slug string) (Page, error)
	GetPageSectionByID(ctx context.Context, id uuid.UUID) (PageSection, error)
	GetPageTranslationByLang(ctx context.Context, arg GetPageTranslationByLangParams) (PageTranslation, error)
	GetPageTranslations(ctx context.Context, pageID uuid.UUID) ([]PageTranslation, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductCategoryByID(ctx context.Context, id uuid.UUID) (ProductCategory, error)
	GetProductCategoryBySlug(ctx context.Context, slug string) (ProductCategory, error)
	GetProductImages(ctx context.Context, productID uuid.UUID) ([]GetProductImagesRow, error)
	GetProductTranslationBySlugAndLang(ctx context.Context, arg GetProductTranslationBySlugAndLangParams) (GetProductTranslationBySlugAndLangRow, error)
	GetProductTranslations(ctx context.Context, productID uuid.UUID) ([]ProductTranslation, error)
	GetPublishedPageBySlug(ctx context.Context, slug string) (Page, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	GetSectionTranslations(ctx context.Context, sectionID uuid.UUID) ([]PageSectionTranslation, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (GetSessionByTokenRow, error)
	GetSettingByKey(ctx context.Context, settingKey string) (SiteSetting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	ListActivePageSections(ctx context.Context, pageID uuid.UUID) ([]PageSection, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListContactInquiries(ctx context.Context, arg ListContactInquiriesParams) ([]ContactInquiry, error)
	ListContentRevisions(ctx context.Context, arg ListContentRevisionsParams) ([]ListContentRevisionsRow, error)
	ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]ListMediaFilesRow, error)
	ListNewsArticles(ctx context.Context, arg ListNewsArticlesParams) ([]ListNewsArticlesRow, error)
	ListPageSections(ctx context.Context, pageID uuid.UUID) ([]PageSection, error)
	ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListProductCategories(ctx context.Context) ([]ProductCategory, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListPublicSettings(ctx context.Context) ([]ListPublicSettingsRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSiteSettings(ctx context.Context) ([]SiteSetting, error)
	ListThemeConfigs(ctx context.Context) ([]ThemeConfig, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	PermanentDeleteContactInquiry(ctx context.Context, id uuid.UUID) error
	PermanentDeleteMedia(ctx context.Context, id uuid.UUID) error
	PermanentDeleteNewsArticle(ctx context.Context, id uuid.UUID) error
	PermanentDeletePage(ctx context.Context, id uuid.UUID) error
	PermanentDeleteProduct(ctx context.Context, id uuid.UUID) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	ReplaceMediaFile(ctx context.Context, arg ReplaceMediaFileParams) (MediaFile, error)
	RestoreMedia(ctx context.Context, id uuid.UUID) error
	RestoreNewsArticle(ctx context.Context, id uuid.UUID) error
	RestorePage(ctx context.Context, id uuid.UUID) error
	RestoreProduct(ctx context.Context, id uuid.UUID) error
	SetActiveTheme(ctx context.Context, code string) error
	SetPageStatus(ctx context.Context, arg SetPageStatusParams) (Page, error)
	SoftDeleteContactInquiry(ctx context.Context, id uuid.UUID) error
	SoftDeleteMedia(ctx context.Context, id uuid.UUID) error
	SoftDeleteNewsArticle(ctx context.Context, id uuid.UUID) error
	SoftDeletePage(ctx context.Context, id uuid.UUID) error
	SoftDeletePageSection(ctx context.Context, id uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	SoftDeleteProductCategory(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateContactInquiryStatus(ctx context.Context, arg UpdateContactInquiryStatusParams) (ContactInquiry, error)
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (MediaFile, error)
	UpdateNewsArticle(ctx context.Context, arg UpdateNewsArticleParams) (NewsArticle, error)
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePageSection(ctx context.Context, arg UpdatePageSectionParams) (PageSection, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateSectionSortOrder(ctx context.Context, arg UpdateSectionSortOrderParams) error
	UpdateSessionReauth(ctx context.Context, sessionToken string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertNewsTranslation(ctx context.Context, arg UpsertNewsTranslationParams) (NewsArticleTranslation, error)
	UpsertPageSectionTranslation(ctx context.Context, arg UpsertPageSectionTranslationParams) (PageSectionTranslation, error)
	UpsertPageTranslation(ctx context.Context, arg UpsertPageTranslationParams) (PageTranslation, error)
	UpsertProductCategoryTranslation(ctx context.Context, arg UpsertProductCategoryTranslationParams) (ProductCategoryTranslation, error)
	UpsertProductTranslation(ctx context.Context, arg UpsertProductTranslationParams) (ProductTranslation, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (SiteSetting, error)
	UpsertThemeConfig(ctx context.Context, arg UpsertThemeConfigParams) (ThemeConfig, error)
}

var _ Querier = (*Queries)(nil)
