// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveThemeConfig = `-- name: GetActiveThemeConfig :one
SELECT id, code, name, is_active, tokens, created_at, updated_at FROM theme_configs
WHERE is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveThemeConfig(ctx context.Context) (ThemeConfig, error) {
	row := q.db.QueryRow(ctx, getActiveThemeConfig)
	var i ThemeConfig
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, setting_group, setting_key, value, is_public, description, updated_by, created_at, updated_at FROM site_settings WHERE setting_key = $1
`

func (q *Queries) GetSettingByKey(ctx context.Context, settingKey string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, settingKey)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SettingGroup,
		&i.SettingKey,
		&i.Value,
		&i.IsPublic,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicSettings = `-- name: ListPublicSettings :many
SELECT setting_key, value FROM site_settings
WHERE is_public = TRUE
`

type ListPublicSettingsRow struct {
	SettingKey string `json:"setting_key"`
	Value      []byte `json:"value"`
}

func (q *Queries) ListPublicSettings(ctx context.Context) ([]ListPublicSettingsRow, error) {
	rows, err := q.db.Query(ctx, listPublicSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicSettingsRow
	for rows.Next() {
		var i ListPublicSettingsRow
		if err := rows.Scan(&i.SettingKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettings = `-- name: ListSiteSettings :many
SELECT id, setting_group, setting_key, value, is_public, description, updated_by, created_at, updated_at FROM site_settings
ORDER BY setting_group ASC, setting_key ASC
`

func (q *Queries) ListSiteSettings(ctx context.Context) ([]SiteSetting, error) {
	rows, err := q.db.Query(ctx, listSiteSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteSetting
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.ID,
			&i.SettingGroup,
			&i.SettingKey,
			&i.Value,
			&i.IsPublic,
			&i.Description,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemeConfigs = `-- name: ListThemeConfigs :many
SELECT id, code, name, is_active, tokens, created_at, updated_at FROM theme_configs
ORDER BY code ASC
`

func (q *Queries) ListThemeConfigs(ctx context.Context) ([]ThemeConfig, error) {
	rows, err := q.db.Query(ctx, listThemeConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThemeConfig
	for rows.Next() {
		var i ThemeConfig
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.Tokens,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveTheme = `-- name: SetActiveTheme :exec
UPDATE theme_configs
SET is_active = (code = $1),
    updated_at = NOW()
`

func (q *Queries) SetActiveTheme(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, setActiveTheme, code)
	return err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO site_settings (setting_group, setting_key, value, is_public, description, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (setting_key) DO UPDATE
SET setting_group = EXCLUDED.setting_group,
    value = EXCLUDED.value,
    is_public = EXCLUDED.is_public,
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, setting_group, setting_key, value, is_public, description, updated_by, created_at, updated_at
`

type UpsertSettingParams struct {
	SettingGroup string      `json:"setting_group"`
	SettingKey   string      `json:"setting_key"`
	Value        []byte      `json:"value"`
	IsPublic     bool        `json:"is_public"`
	Description  pgtype.Text `json:"description"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.SettingGroup,
		arg.SettingKey,
		arg.Value,
		arg.IsPublic,
		arg.Description,
		arg.UpdatedBy,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SettingGroup,
		&i.SettingKey,
		&i.Value,
		&i.IsPublic,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertThemeConfig = `-- name: UpsertThemeConfig :one
INSERT INTO theme_configs (code, name, is_active, tokens)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    tokens = EXCLUDED.tokens,
    updated_at = NOW()
RETURNING id, code, name, is_active, tokens, created_at, updated_at
`

type UpsertThemeConfigParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Tokens   []byte `json:"tokens"`
}

func (q *Queries) UpsertThemeConfig(ctx context.Context, arg UpsertThemeConfigParams) (ThemeConfig, error) {
	row := q.db.QueryRow(ctx, upsertThemeConfig,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.Tokens,
	)
	var i ThemeConfig
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
